### ISSUE TITLE
Issue with embedding Tab widget inside an ipyvuetify layout

### ISSUE THREAD

**Issue by astrofrog** [mariobuikhuizen/ipyvuetify#1]
I have been experimenting with embedding ipywidgets inside ipyvuetify layouts, and for the most part have been successful, but when trying to embed a ``Tab`` widget, the tabs become unresponsive:

```python
import ipyvuetify as v
from ipywidgets import Button, Tab

button1 = Button(description='button 1')
button2 = Button(description='button 2')

tab = Tab(children=[button1, button2])
vtab = v.Layout(children=[tab])
```

The rendering is fine, but the tabs in the ``vtab`` output don't respond to clicks:

<img width="1129" alt="Screenshot 2019-05-20 at 19 30 22" src="https://user-images.githubusercontent.com/314716/58043686-badc6580-7b35-11e9-98aa-ebd70da32b1c.png">

There are no error messages in the Javascript console.

Of course, one shouldn't really be using the tab widget, as vuetify has better options, but I'm reporting this anyway in case it highlights an issue that might occur with other more relevant widgets.

**Comment by SaOgaz** [comment]
Confirmed that this fix works for me and my use case with glue-jupyter.
