### ISSUE TITLE
TeX equations

### ISSUE THREAD

**Issue by DohunLee** [mariobuikhuizen/ipyvuetify#100]
When using the example code (2 histograms, 1 line chart with 2 sliders). Adding a slider code to:
```
slider = v.Slider(thumb_label='always', class_="px-4", v_model=30, label='Test $\widehat{F}$ in N')
widgets.link((slider, 'v_model'), (hist, 'bins'))
slider
```
displays correctly in notebook:
![Screenshot 2020-10-26 112810](https://user-images.githubusercontent.com/70583102/97162199-268d1e00-177f-11eb-8328-067a51f90f4f.png)

yet false when streamed to browser:
![Screenshot 2020-10-26 113057](https://user-images.githubusercontent.com/70583102/97162235-3573d080-177f-11eb-844a-cded514026a3.png)

Any ideas how to solve this?

**Comment by mariobuikhuizen** [comment]
What do you mean by 'streamed to browser'? Are you using Voila or Voila-vuetify?

**Comment by DohunLee** [comment]
@mariobuikhuizen 
Hello, thank you for your reply!
with "streamed to browser", I mean running the program using `voila --template [template name] [directory of file]` in terminal. Which opens my internet browser showing the web application. By using the template and the vuetify functions, it should be voila-vuetify, but I might be misunderstanding something.

**Comment by mariobuikhuizen** [comment]
I fixed this in the base voila-vuetify template: https://github.com/voila-dashboards/voila-vuetify/pull/41/commits/9d9595b2a8bb7714eace112ce3b11be71ec8134e

**Comment by DohunLee** [comment]
Thank you very much @mariobuikhuizen . It fixed the Issue.
