### ISSUE TITLE
Cannot write white spaces in a Alert object 

### ISSUE THREAD

**Issue by 12rambau** [mariobuikhuizen/ipyvuetify#103]
I try to display n progress bar in an Alert (instead of using the vuetify progress element I know). 

I created a little script that does a nice output as a str : 
```py 
def update_progress(progress, msg='Progress', bar_length=30):
    plain_char = '█'
    empty_char = ' '
    progress = float(progress)
    block = int(round(bar_length * progress))

    text = f'{msg}: |{plain_char * block + empty_char * (bar_length - block)}| {progress *100:.1f}%'
    
    return text
```

when I print the output, I get the following : 
![Capture d’écran 2020-11-12 à 11 18 26](https://user-images.githubusercontent.com/12596392/98927445-d3360200-24d8-11eb-8cbf-2c770c2ba572.png)

and when I insert it as a child in an Alert component : 
![Capture d’écran 2020-11-12 à 11 19 09](https://user-images.githubusercontent.com/12596392/98927503-e8ab2c00-24d8-11eb-9a52-cd2f598e1913.png)

First problem, the spaces have bee trimed, second problem it's changing the block ascii character to a wider one. 
Is it normal ?

**Comment by mariobuikhuizen** [comment]
Yes that's normal, it's a 'feature' HTML: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace

Using the `pre` tag will preserve whitespace:
```python
v.Html(tag='pre', children=['a                 mess age'])
```

**Comment by 12rambau** [comment]
Thanks a lot, 
As the question is not related to any bug but usage I have taken the liberty to cross posted it on [SO](https://stackoverflow.com/questions/64805545/cannot-write-white-spaces-in-a-alert-object-in-ipyvuetify/64805546#64805546) because it's better referenced than github issues on Google.
