### ISSUE TITLE
How to click an ipyvuetify button programmatically

### ISSUE THREAD

**Issue by joseberlines** [mariobuikhuizen/ipyvuetify#107]
Assume I have a code with a button coded in ipyvuetify

```
v_btn_load  = vue.Btn(class_='mx-2 light-red darken-1', 
                           children=[vue.Icon(left=True, children=['get_app']),'Load data'])

def on_click_load(widget, event, data):
    #pseudo code: load file
    print("button run")
                
v_btn_load.on_event('click', on_click_load)
```
How do I run (click) programmatically the v_btn_load button?
`v_btn_load.click() does not work`

I posted the question in SO:
https://stackoverflow.com/questions/65053418/run-programmatically-an-ipyvuetify-button

Thanks

**Comment by 12rambau** [comment]
As the question is answered in SO can you please close your issue ?
