### ISSUE TITLE
How to limit the possible extension with FilInput ? 

### ISSUE THREAD

**Issue by 12rambau** [mariobuikhuizen/ipyvuetify#112]
I used the FileInput widget and try to limit the possible extensions. 
I adapted the key words that I found in the vuetify doc : https://vuetifyjs.com/en/components/file-inputs

```py
import ipyvuetify as v

input_file = FileInput(
    multiple = False, 
    accept = "image/png, image/jpeg, image/bmp"
)
```

but then I can select virtually everything. 
Is this parameter ignored ?

**Comment by mariobuikhuizen** [comment]
Yes, only a few properties supported right now.

**Comment by 12rambau** [comment]
Ok so i'll let this one open for now and will use my app logic to accept or refuse the file.

**Comment by 12rambau** [comment]
thanks
