### ISSUE TITLE
spellcheck prop in text input fields

### ISSUE THREAD

**Issue by guimillet** [mariobuikhuizen/ipyvuetify#128]
Although Vuetify does not mention spellcheck as prop of v-textarea, sub classing VuetifyTemplate with the template:
```python
class TextareaNospellcheck(v.VuetifyTemplate):
    template = traitlets.Unicode('<v-textarea spellcheck="false"></v-textarea>').tag(sync=True)
```
provides a v-textarea with spell check disabled.

However, `v.Textarea(spellcheck="false")` does not work: the spellcheck attribute is not passed to the textarea tag. Is this due to the absence of spellcheck prop of v-textarea?

**Comment by mariobuikhuizen** [comment]
`spellcheck` is not a prop of `v-textarea` but an HTML attribute. It can be set in `attributes` : https://ipyvuetify.readthedocs.io/en/latest/usage.html?highlight=attributes#regular-html-tags

```python
v.Textarea(attributes={'spellcheck': False})
```
