### ISSUE TITLE
Equivalent of widgets.output

### ISSUE THREAD

**Issue by samiit** [mariobuikhuizen/ipyvuetify#134]
Hi everyone,

How can I update the output of any widget, say, an output placeholder where I display an image, a datatable or anything of the like?

In ipywidgets, it is quite simply by using:
```
out_pl = widgets.Output()
out_pl.clear_output()

with out_pl:
    display(img)
    
```

I am especially in need of updating the output of a pandas dataframe, displayed as an ipyvuetify data-table. How can I update the values of the table?

Thanks and regards,
Sam

**Comment by 12rambau** [comment]
@mariobuikhuizen will correct me if I'm wrong but in `ipyvuetfy` if you are using the `v.DataTable` widget, you can udate the items trait at any time to update the display:

``` python 
import ipyvuetify as v

headers = [
        { 'text': 'Dessert (100g serving)', 'value': 'name'},
        { 'text': 'Calories', 'value': 'calories' },
        { 'text': 'Fat (g)', 'value': 'fat' },
        { 'text': 'Carbs (g)', 'value': 'carbs' },
        { 'text': 'Protein (g)', 'value': 'protein' },
        { 'text': 'Iron (%)', 'value': 'iron' },
]

items = [
    {
        'name': 'Frozen Yogurt',
        'calories': 159,
        'fat': 6.0,
        'carbs': 24,
        'protein': 4.0,
        'iron': '1%',
    },
    {
        'name': 'Ice cream sandwich',
        'calories': 237,
        'fat': 9.0,
        'carbs': 37,
        'protein': 4.3,
        'iron': '1%',
    }
 ]
toto = v.DataTable(
    headers = headers,
    items = items
)

toto
```

Now to update the `items` trait of your DataTable : 
```python 
new_item = {
    'name': 'Cupcake',
    'calories': 305,
    'fat': 3.7,
    'carbs': 67,
    'protein': 4.3,
    'iron': '8%'
}

toto.items =  toto.items + [new_item]
```

And the previously displayed toto DataTable will be updated. 


This behavior will be the same for all trait of all widgets, they can be changed whenever you want.

**Comment by samiit** [comment]
Thanks @12rambau , this clarified much.

Sam
