### ISSUE TITLE
v.Select dropdown does not update Python value after user makes a selection

### ISSUE THREAD

**Issue by NumesSanguis** [mariobuikhuizen/ipyvuetify#145]
Thank you for this great repository!
As the title describes, I ran into an issue.

# Code to reproduce
In a Jupyter notebook, executing the following code:
Cell 1:
```python
import ipyvuetify as v
dropdown = v.Select(label="Choose:", items=["A", "B"], value='A')
dropdown
```

Cell 2:
```python
dropdown.value
```
Cell 2 will display `'A'` as expected.

However, if the user then selects `'B'` from the drop down menu, the python value `dropdown.value` does not change.
Or in other words, executing Cell 2 again will still result in `'A'`.

## Screenshot
![2021-05-16_ipyvuetify_select-issue](https://user-images.githubusercontent.com/8008618/118397350-776a5280-b68e-11eb-93e6-46f2077d0c0d.png)

## Extra info
If `value='A'` is not specified, the above issue is still the same, but instead of `'A'`, it displays `None`.

# System
- OS: Ubuntu 20.04

Conda env:
- Python: 3.7.10
- ipyvue: 1.5.0 (conda-forge)
- ipyvuetify: 1.6.2 (conda-forge)
- ipywidgets: 7.6.3
- voila 0.2.10 (conda-forge)
- voila-vuetify (conda-forge)

**Comment by mariobuikhuizen** [comment]
Thanks for reporting this issue, but this is not a bug see: https://ipyvuetify.readthedocs.io/en/latest/usage.html#reading-the-value.

**Comment by NumesSanguis** [comment]
Thank you for the quick response, and indeed this was not a bug. Sorry, I completely missed this part in the documentation.

I spend most time learning about this library using the [Example.ipynb](https://github.com/mariobuikhuizen/ipyvuetify/blob/master/examples/Examples.ipynb) you provided.
Do you think it's a good idea to add an example of `v_model` there?
If not, I can close this issue (or feel free to close it).
