### ISSUE TITLE
add event listener to VuetifyTemplate subclasses

### ISSUE THREAD

**Issue by gioxc88** [mariobuikhuizen/ipyvuetify#147]
In the [`example.ipynb`](https://github.com/mariobuikhuizen/ipyvuetify/blob/master/examples/Examples%20template.ipynb) there is a `PandasDataFrame` class which inherits from `VuetifyTemplate`.

How can I add a `on_event('click:row')` to it?
I am able to do it if I use `v.DataTable` but not idea about how to add it to `PandasDataFrame`.

Can anyone help me on this?
Many thanks

**Comment by mariobuikhuizen** [comment]
An example of an event is in the same example.ipynb, look for `@click="menu_click(index)"` in the template and a matching `def vue_menu_click(self, data):` in the python code. It doesn't work with `on_event` like in the pure python version.

**Comment by gioxc88** [comment]
> An example of an event is in the same example.ipynb, look for `@click="menu_click(index)"` in the template and a matching `def vue_menu_click(self, data):` in the python code. It doesn't work with `on_event` like in the pure python version.

Thank you for the answer, I am already aware of that but this way I will not be able to reuse components as every event must be defined in the same template which is very limiting

Is there no other solution for achieving this?
Say for example I define my custom `PandasDataFrame` and then I want to use this in another component while being able to control events.

The only way that I can think of is to define custom events using `emit` directly inside the template.

**Comment by gioxc88** [comment]
> An example of an event is in the same example.ipynb, look for `@click="menu_click(index)"` in the template and a matching `def vue_menu_click(self, data):` in the python code. It doesn't work with `on_event` like in the pure python version.

I'll rephrase:

how can I add events to `VuetifyTemplate` subclasses after the instance creation?

Also can you confirm that `def vue_menu_click(self, data)` does not accept additional arguments?

for example if I want to pass to the `vue_some_function(self, data, item)`, where `item` is define in the template, this it is not possible as I always get an error on the python side saying `missing positional argument item`

could you please clarify on that?

**Comment by mariobuikhuizen** [comment]
You can set a function in an instance variable and call that from `def vue_menu_click`.

`data` can be a dict or list, so you can put anything in it. In the example you can replace `index` with `item`.

**Comment by gioxc88** [comment]
Thanks makes sense now!

**Comment by gboaviagem** [comment]
Hi! This thread showed up to reignite my hope of solving my problem, but I **still can't make it work**. As with @gioxc88 I need simply a callback that provide to a function outside the DataTable object (made with VuetifyTemplate) the content of the row the user just clicked. **I was able to perform a similar task in the MyMenu class, but not in the PandasDataFrame**. Here is how far I made:

### [success] Callback from "MyMenu" to external function

Starting simple, I took the MyMenu class in the `example.ipynb` notebook and was able to successfully send the event-generated data to a Button, via external function:

```python
import traitlets

class MyMenu(v.VuetifyTemplate):
    color = traitlets.Unicode('primary').tag(sync=True)
    items = traitlets.List(['red', 'green', 'purple']).tag(sync=True)
    button_text = traitlets.Unicode('menu').tag(sync=True)
    template = traitlets.Unicode('''
        <v-layout>
            <v-menu offset-y>
               <template v-slot:activator="{ on }">
                    <v-btn
                            :color="color"
                            class="white--text"
                            v-on="on">
                        {{ button_text }}
                    </v-btn>
                </template>

                <v-list>
                    <v-list-item
                            v-for="(item, index) in items"
                            :key="index"
                            @click="callback(index)">
                        <v-list-item-title>{{ item }}</v-list-item-title>
                    </v-list-item>
                </v-list>
            
            
            </v-menu>
        </v-layout>''').tag(sync=True)
    on_click = None  # This must receive a function which will be called inside `self.vue_callback()`
    
    def vue_callback(self, data):
        self.on_click(data)

btn = v.Btn(children=["Nenhum click."])
        
def click_response(data):
    btn.children = [str(data)]
    
menu = MyMenu()
menu.on_click = click_response
menu

v.Html(tag='div', class_='d-flex flex-column', children=[
    btn,
    menu,
])
```

### [Failed] Callback from "PandasDataFrame" to external function

I tried to replicate the logic as close as possible, but in my test the Button content never changes, despite many interactions with the DataTable:

```python
import pandas as pd
import traitlets
import ipyvuetify as v
import json

class PandasDataFrame(v.VuetifyTemplate):
    """
    Vuetify DataTable rendering of a pandas DataFrame
    
    Args:
        data (DataFrame) - the data to render
        title (str) - optional title
    """
    
    headers = traitlets.List([]).tag(sync=True, allow_null=True)
    items = traitlets.List([]).tag(sync=True, allow_null=True)
    search = traitlets.Unicode('').tag(sync=True)
    title = traitlets.Unicode('DataFrame').tag(sync=True)
    index_col = traitlets.Unicode('').tag(sync=True)
    template = traitlets.Unicode('''
        <template>
          <v-card>
            <v-card-title>
              <span class="title font-weight-bold">{{ title }}</span>
              <v-spacer></v-spacer>
                <v-text-field
                    v-model="search"
                    append-icon="mdi-magnify"
                    label="Search ..."
                    single-line
                    hide-details
                ></v-text-field>
            </v-card-title>
            <v-data-table
                :headers="headers"
                :items="items"
                :search="search"
                :item-key="index_col"
                show-select
                :footer-props="{'items-per-page-options': [5, 10, 25, 50, 250, 500]}"
            >
                <template v-slot:no-data>
                  <v-alert :value="true" color="error" icon="mdi-alert">
                    Sorry, nothing to display here :(
                  </v-alert>
                </template>
                <template v-slot:no-results>
                    <v-alert :value="true" color="error" icon="mdi-alert">
                      Your search for "{{ search }}" found no results.
                    </v-alert>
                </template>


                <template v-slot:items="rows">
                  <td v-for="(element, label, index) in rows.item"
                      @click=callback(element)
                      >
                    {{ element }}
                  </td>
                </template>


            </v-data-table>
          </v-card>
        </template>
        ''').tag(sync=True)
    on_click = None  # This must receive a function which will be called inside `self.vue_callback()`
    
    def vue_callback(self, data):
        self.on_click(data)
    
    def __init__(self, *args, 
                 data=pd.DataFrame(), 
                 title=None,
                 **kwargs):
        super().__init__(*args, **kwargs)
        data = data.reset_index()
        self.index_col = data.columns[0]
        headers = [{
              "text": col,
              "value": col
            } for col in data.columns]
        headers[0].update({'align': 'left', 'sortable': True})
        self.headers = headers
        self.items = json.loads(
            data.to_json(orient='records'))
        if title is not None:
            self.title = title

    
iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
test = PandasDataFrame(data = iris, title='Iris')

btn = v.Btn(children=["Nenhum click."])
        
def click_response(data):
    btn.children = [str(data)]

test.on_click = click_response

v.Html(tag='div', class_='d-flex flex-column', children=[
    btn,
    test,
])
```

I suspect it has something to do with the `v-for` sintax, but it is really not clear to me.

Any help is appreciated, honestly! Thanks in advance.
