### ISSUE TITLE
Registering an external vue component using requirejs

### ISSUE THREAD

**Issue by tedwards-flf** [mariobuikhuizen/ipyvuetify#153]
Hi, I'm attempting to use the [`vue-google-charts`](https://www.npmjs.com/package/vue-google-charts) javascript module with ipyvuetify. I have the following code in my classic jupyter notebook:

```python
import ipyvuetify as v
import traitlets

class VuetifyTest(v.VuetifyTemplate):
    template = traitlets.Unicode(TEMPLATE).tag(sync=True)

VuetifyTest()
```

where TEMPLATE is defined as an html string:

```html
<script>
module.exports = {
    beforeCreate: function () {
        requirejs(['https://cdn.jsdelivr.net/npm/vue-google-charts@0.3.3/dist/vue-google-charts.browser.js'], (VueGChart) => {
            console.log("Vue google charts successfully imported);
            this.$options.components.GChart = VueGChart.GChart;
        });
    },
    
    data: () => ({
      chartData: [
        ["Year", "Sales", "Expenses", "Profit"],
        ["2014", 1000, 400, 200],
        ["2015", 1170, 460, 250],
        ["2016", 660, 1120, 300],
        ["2017", 1030, 540, 350]
      ],
      chartOptions: {
        chart: {
          title: "Company Performance",
          subtitle: "Sales, Expenses, and Profit: 2014-2017"
        }
      },
    })
}

</script>

<template>
    <div>
    <h1>Example Google Chart </h1>
    <GChart
        type="ColumnChart"
        :data="chartData"
        :options="chartOptions"
    />
    </div>
</template>
```

However, when I run this it won't render the google chart. I checked the browser javascript console and saw this error:
```
vue.runtime.esm.js:1888 ReferenceError: chartData is not defined
```

I highly suspect this is an issue with the component registration, because if I replace `<GChart`  with something else like `<MisspelledGChart` I get the same error.

**Comment by mariobuikhuizen** [comment]
You can't use `data` in a vuetify component, this is handled by the framework and used to link traitlets. I could get it to work with a few tweaks:
```python
import ipyvuetify as v
import traitlets

class VuetifyTest(v.VuetifyTemplate):
    template = traitlets.Unicode(TEMPLATE).tag(sync=True)

    loaded = traitlets.Bool(False).tag(sync=True)
    chartData = traitlets.List(default_value=[
        ["Year", "Sales", "Expenses", "Profit"],
        ["2014", 1000, 400, 200],
        ["2015", 1170, 460, 250],
        ["2016", 660, 1120, 300],
        ["2017", 1030, 540, 350]
    ]).tag(sync=True)
    chartOptions = traitlets.Dict({
        'chart': {
            'title': "Company Performance",
            'subtitle': "Sales, Expenses, and Profit: 2014-2017"
        }
    }).tag(sync=True)

VuetifyTest()
```

```html
<script>
module.exports = {
  beforeCreate() {
    requirejs(['https://cdn.jsdelivr.net/npm/vue-google-charts@0.3.3/dist/vue-google-charts.browser.js'], (VueGChart) => {
      console.log("Vue google charts successfully imported");
      this.$options.components.GChart = VueGChart.GChart;
      this.loaded=true
    });
  },
}
</script>

<template>
  <div>
    <h1>Example Google Chart </h1>
    <GChart
      v-if="loaded"
      type="ColumnChart"
      :data="chartData"
      :options="chartOptions"
    />
  </div>
</template>
```

This is awesome, I didn't know this could be done!

**Comment by tedwards-flf** [comment]
> You can't use `data` in a vuetify component, this is handled by the framework and used to link traitlets. I could get it to work with a few tweaks:
> 
> ```python
> import ipyvuetify as v
> import traitlets
> 
> class VuetifyTest(v.VuetifyTemplate):
>     template = traitlets.Unicode(TEMPLATE).tag(sync=True)
> 
>     loaded = traitlets.Bool(False).tag(sync=True)
>     chartData = traitlets.List(default_value=[
>         ["Year", "Sales", "Expenses", "Profit"],
>         ["2014", 1000, 400, 200],
>         ["2015", 1170, 460, 250],
>         ["2016", 660, 1120, 300],
>         ["2017", 1030, 540, 350]
>     ]).tag(sync=True)
>     chartOptions = traitlets.Dict({
>         'chart': {
>             'title': "Company Performance",
>             'subtitle': "Sales, Expenses, and Profit: 2014-2017"
>         }
>     }).tag(sync=True)
> 
> VuetifyTest()
> ```
> 
> ```
> <script>
> module.exports = {
>   beforeCreate() {
>     requirejs(['https://cdn.jsdelivr.net/npm/vue-google-charts@0.3.3/dist/vue-google-charts.browser.js'], (VueGChart) => {
>       console.log("Vue google charts successfully imported");
>       this.$options.components.GChart = VueGChart.GChart;
>       this.loaded=true
>     });
>   },
> }
> </script>
> 
> <template>
>   <div>
>     <h1>Example Google Chart </h1>
>     <GChart
>       v-if="loaded"
>       type="ColumnChart"
>       :data="chartData"
>       :options="chartOptions"
>     />
>   </div>
> </template>
> ```
> 
> This is awesome, I didn't know this could be done!

That's fantastic! I've been struggling with this for a while, I was beginning to think it was impossible. Thanks for your help, this solves my problem

**Comment by ehsanshahidi** [comment]
Apologies if this is a silly question. I am able to get the Google Charts example as @mariobuikhuizen suggests. But for the life of me I cannot get `vue-ag-grid` to work. It feels like it is a problem with the way I am using `requirejs` within `ipyvuetify`. I see no errors on the console,  it just doesn't load anything. Any suggestion (even on how to debug) would be appreciated.
Here's my code (trying to replicate this `vue-ag-grid` [example](https://www.ag-grid.com/vue-data-grid/getting-started/)):
```python
import ipyvuetify as v
import traitlets
class AGTest(v.VuetifyTemplate):
    template_file = 'ag.vue'
    loaded = traitlets.Bool(False).tag(sync=True)
    columnDefs = traitlets.List(default_value=[
        {'field': "make"},
        {'field': "model"}
    ]).tag(sync=True)

    rowData = traitlets.List(default_value=[
        {'make': "Toyota", 'model': "Celica"},
        {'make': "Ford", 'model': "Mondeo"},
        {'make': "Porsche", 'model': "Boxter"}
    ]).tag(sync=True)

```
and here's my template:
```javascript
<script>
var exports = {};
module.exports = {
  beforeCreate() {
    requirejs(["https://cdn.jsdelivr.net/npm/ag-grid-vue@27.1.0/main.min.js"], (agGrid) => {
      console.log("AG Grid imported");
      this.$options.components.AgGridVue = agGrid.AgGridVue;
      this.loaded=true
    });
  },
}
</script>

<template>
  <AgGridVue
    style="width: 500px; height: 50px"
    :columnDefs="columnDefs"
    :rowData="rowData"
  >
  </AgGridVue>
</template>

```
