### ISSUE TITLE
Can't set new value of Select when the old value is part of the new item list

### ISSUE THREAD

**Issue by rg98** [mariobuikhuizen/ipyvuetify#158]
Hi, 
when I change the item list of a v.Select element, then I could normally set the new value to the first entry of the list. When the old value is also part of the new list the value get not changed.
As a workaround I extended the value by more information and kept the text the same, but it feels strange to me.
Kind regards
rg98

**Comment by mariobuikhuizen** [comment]
Hi rg98,

Can you post a minimal example that shows this issue?

**Comment by rg98** [comment]
Hi Mario,

How could I post the example? Sorry but I have no experience in using GitHub for development. Do you mean on GitHub or in a short mail?

Kind regards
Ralph

**Comment by mariobuikhuizen** [comment]
You can post the code in a comment (See https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks on how to format), like this:
```python
import ipyvutify as v

# Show a button
v.Btn(color='primary', children['hello'])
```

**Comment by rg98** [comment]
Sorry Mario,

I got this message mixed up with the other issue, sorry.

The problem could be reproduced by the following notebook:
```
import ipyvuetify as v
```

```
d_items = ['item 1', 'item 2', 'item 3']
d_item = d_items[0]

d_timestamps = [
    '2021-06-24 07:55',
    '2021-06-23 07:55',
    '2021-06-22 07:55',
    '2021-06-21 07:55',
]

n_timestamps = [
    '2021-06-24 07:55',
    '2021-06-23 07:55',
    '2021-06-22 07:55',
    '2021-05-21 07:55',
]

i_timestamps = [
    '2021-03-24 07:55',
    '2021-03-23 07:55',
    '2021-03-22 07:55',
    '2021-03-21 07:55',
]

d_times_header = [
    { "text": 'Name', "align": 'end', "value": 'name' },
    { "text": 'Value', "align": 'start', "value": 'value' },
]

d_times = [
    { "name": 'Start', "value": '2021-06-24 07:55:37' },
    { "name": 'End', "value": '2021-06-24 08:52:31' },
]
```

```
s_timestamp_items = list(map(lambda i: {"text": i, "value": i}, d_timestamps))
```

```
s_select = v.Select(items=s_timestamp_items,
                    label='Timestamp',
                    value=d_timestamps[0])
s_select
```

```
s_items = list(map(lambda i: v.Radio(label=i, value=i), d_items))
s_item_list = v.RadioGroup(dens=True,
                           mandatory=True,
                           value=d_item,
                           children=s_items)
s_item_list
```

```
def on_s_item_change(widget, event, data):
    global d_item, d_items, s_items, s_select
    d_item = data
    if data == d_items[0]:
        s_timestamp_items = list(map(lambda i: {"text": i, "value": i}, d_timestamps))
        s_select.items = s_timestamp_items
        s_select.value = d_timestamps[0]
    elif data == d_items[1]:
        s_timestamp_items = list(map(lambda i: {"text": i, "value": i}, n_timestamps))
        s_select.items = s_timestamp_items
        s_select.value = n_timestamps[0]
    else:
        s_timestamp_items = list(map(lambda i: {"text": i, "value": i}, i_timestamps))
        s_select.items = s_timestamp_items
        s_select.value = i_timestamps[0]

s_item_list.on_event('change', on_s_item_change)
```

When you copy the code snippets into successional cells and execute all of them, then you should get a Select and a RadioGroup. The Select could choose from four timestamps. the timestamps differ dependent on the RadioGroup.
If you select one of the equal entries of the Select and switch the set by changing the RadioGroup selection, the display does not change despite the setting of the value.
When you choose a value which is not available in the other set, the Select will be unset. Choosing the third set always show the intended behaviour.

If I watched carefully enough, I think it depends on the combination of the list elements in the items. when the values are the same from beginning to the selection, then nothing get changed, if there are different values above, then the behaviour is as expected.

Kind regards
Ralph

**Comment by mariobuikhuizen** [comment]
In ipyvuetify `v_model` is used instead of `value` in ipywidgets (see: https://ipyvuetify.readthedocs.io/en/latest/usage.html#reading-the-value).

So changing these parts will fix it:
```python
...
s_select = v.Select(items=s_timestamp_items,
                    label='Timestamp',
                    v_model=d_timestamps[0]
...
s_item_list = v.RadioGroup(dens=True,
                           mandatory=True,
                           v_model=d_item,
                           children=s_items)
...
def on_s_item_change(widget, event, data):
    global d_item, d_items, s_items, s_select
    d_item = data
    if data == d_items[0]:
        s_timestamp_items = list(map(lambda i: {"text": i, "value": i}, d_timestamps))
        s_select.items = s_timestamp_items
        s_select.v_model = d_timestamps[0]
    elif data == d_items[1]:
        s_timestamp_items = list(map(lambda i: {"text": i, "value": i}, n_timestamps))
        s_select.items = s_timestamp_items
        s_select.v_model = n_timestamps[0]
    else:
        s_timestamp_items = list(map(lambda i: {"text": i, "value": i}, i_timestamps))
        s_select.items = s_timestamp_items
        s_select.v_model = i_timestamps[0]
```

**Comment by rg98** [comment]
Hi Mario,

thank you this solved my problem. Sorry for not reading the manual thoroughly enough.

Kind regards
Ralph

**Comment by mariobuikhuizen** [comment]
No worries, just mentioned it for further details.
