### ISSUE TITLE
Is there an error in documentation?

### ISSUE THREAD

**Issue by rg98** [mariobuikhuizen/ipyvuetify#160]
Hi,

thank you all for the great work on these modules. I like them a lot.

When I tried to follow documentation about "Template Usage", I got confused by the example in fruit-selector.vue. The example shows in line 7 the use of python methods:
```
 <v-btn @click="add_fruit_python()" :disabled="!can_add_from_python">Add from Pyton</v-btn>
```

When I tried this in a event handler, I have to remove the prentices to get the argument of the event.
Are prentices a bug in documentation or are the semantics different for events?

Kind regards
Ralph

**Comment by mariobuikhuizen** [comment]
Hi rg88,

Thanks for reporting this issue. The documentation is correct, the data that could be sent to the python method is not used in the example. It would arguably be better to show how to use the data part in this example.

Indeed, the leaving out the parentheses will send the click event. Also, you could, in addition to the event, add more data by adding it to an array: `@click="add_fruit_python([$event, 'something_else'])"`

**Comment by rg98** [comment]
Hi mariobuikhuize,

thanks for the explanation on how this could be even enhanced.

Regards
Ralph
