### ISSUE TITLE
Event listener to DataTable built with VuetifyTemplate

### ISSUE THREAD

**Issue by gboaviagem** [mariobuikhuizen/ipyvuetify#163]
Hi! I followed the thread #147 closely, but despite the answers making sense, I am having a lot of trouble to make it work.

As with @gioxc88 I need simply a callback that provide to a function outside the DataTable object (made with VuetifyTemplate) **the content of the row the user just clicked** (or the content of the whole dataframe, whatever works). I was able to perform a similar task in the MyMenu class, but not in the PandasDataFrame (both found in the [example.ipynb](https://github.com/mariobuikhuizen/ipyvuetify/blob/master/examples/Examples%20template.ipynb) notebook). Here is how far I made:

### [success] Callback from "MyMenu" to external function

Starting simple, I took the MyMenu class in the `example.ipynb` notebook and was able to successfully send the event-generated data to a Button, via external function:

```python
import traitlets

class MyMenu(v.VuetifyTemplate):
    color = traitlets.Unicode('primary').tag(sync=True)
    items = traitlets.List(['red', 'green', 'purple']).tag(sync=True)
    button_text = traitlets.Unicode('menu').tag(sync=True)
    template = traitlets.Unicode('''
        <v-layout>
            <v-menu offset-y>
               <template v-slot:activator="{ on }">
                    <v-btn
                            :color="color"
                            class="white--text"
                            v-on="on">
                        {{ button_text }}
                    </v-btn>
                </template>

                <v-list>
                    <v-list-item
                            v-for="(item, index) in items"
                            :key="index"
                            @click="callback(index)">
                        <v-list-item-title>{{ item }}</v-list-item-title>
                    </v-list-item>
                </v-list>
            
            
            </v-menu>
        </v-layout>''').tag(sync=True)
    on_click = None  # This must receive a function which will be called inside `self.vue_callback()`
    
    def vue_callback(self, data):
        self.on_click(data)

btn = v.Btn(children=["Nenhum click."])
        
def click_response(data):
    btn.children = [str(data)]
    
menu = MyMenu()
menu.on_click = click_response

v.Html(tag='div', class_='d-flex flex-column', children=[
    btn,
    menu,
])
```

### [Failed] Callback from "PandasDataFrame" to external function

I tried to replicate the logic as close as possible, but in my test the Button content never changes, despite many interactions with the DataTable:

```python
import pandas as pd
import traitlets
import ipyvuetify as v
import json

class PandasDataFrame(v.VuetifyTemplate):
    """
    Vuetify DataTable rendering of a pandas DataFrame
    
    Args:
        data (DataFrame) - the data to render
        title (str) - optional title
    """
    
    headers = traitlets.List([]).tag(sync=True, allow_null=True)
    items = traitlets.List([]).tag(sync=True, allow_null=True)
    search = traitlets.Unicode('').tag(sync=True)
    title = traitlets.Unicode('DataFrame').tag(sync=True)
    index_col = traitlets.Unicode('').tag(sync=True)
    template = traitlets.Unicode('''
        <template>
          <v-card>
            <v-card-title>
              <span class="title font-weight-bold">{{ title }}</span>
              <v-spacer></v-spacer>
                <v-text-field
                    v-model="search"
                    append-icon="mdi-magnify"
                    label="Search ..."
                    single-line
                    hide-details
                ></v-text-field>
            </v-card-title>
            <v-data-table
                :headers="headers"
                :items="items"
                :search="search"
                :item-key="index_col"
                show-select
                :footer-props="{'items-per-page-options': [5, 10, 25, 50, 250, 500]}"
            >
                <template v-slot:no-data>
                  <v-alert :value="true" color="error" icon="mdi-alert">
                    Sorry, nothing to display here :(
                  </v-alert>
                </template>
                <template v-slot:no-results>
                    <v-alert :value="true" color="error" icon="mdi-alert">
                      Your search for "{{ search }}" found no results.
                    </v-alert>
                </template>


                <template v-slot:items="rows">
                  <td v-for="(element, label, index) in rows.item"
                      @click=callback(element)
                      >
                    {{ element }}
                  </td>
                </template>


            </v-data-table>
          </v-card>
        </template>
        ''').tag(sync=True)
    on_click = None  # This must receive a function which will be called inside `self.vue_callback()`
    
    def vue_callback(self, data):
        self.on_click(data)
    
    def __init__(self, *args, 
                 data=pd.DataFrame(), 
                 title=None,
                 **kwargs):
        super().__init__(*args, **kwargs)
        data = data.reset_index()
        self.index_col = data.columns[0]
        headers = [{
              "text": col,
              "value": col
            } for col in data.columns]
        headers[0].update({'align': 'left', 'sortable': True})
        self.headers = headers
        self.items = json.loads(
            data.to_json(orient='records'))
        if title is not None:
            self.title = title

    
iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
test = PandasDataFrame(data = iris, title='Iris')

btn = v.Btn(children=["Nenhum click."])
        
def click_response(data):
    btn.children = [str(data)]

test.on_click = click_response

v.Html(tag='div', class_='d-flex flex-column', children=[
    btn,
    test,
])
```

I suspect it has something to do with the `v-for` sintax, but it is really not clear to me.

Any help is appreciated, honestly! Thanks in advance.

**Comment by mariobuikhuizen** [comment]
Hi @gboaviagem ,

`@click=callback(element)` is missing quotes, it should be `@click="callback(element)"`.

**Comment by gboaviagem** [comment]
Wow @mariobuikhuizen I really appreciate the amazing response time! Specially given I'm trying to incorporate ipyvuetify in a big project. Thanks!

Regarding the suggestion, I did try adding the quotes, but unfortunately it still does not work. The v-slot template ended up like this:
```python
<template v-slot:items="rows">
  <td v-for="(element, label, index) in rows.item"
      @click="callback(element)">
    {{ element }}
  </td>
</template>
```

Am I missing something?

And, just taking the opportunity to learn more, is there any reason why in the `example.ipynb` notebook the `cell_click` method appears without quotes?
```python
<template v-slot:items="rows">
  <td v-for="(element, label, index) in rows.item"
      @click=cell_click(element)
      >
    {{ element }}
  </td>
</template>
```

Thanks again.

**Comment by mariobuikhuizen** [comment]
Turns out, that part of the example doesn't do anything. `items` is not a slot (https://vuetifyjs.com/en/api/v-data-table/#api-slots). Thanks for pointing that out!

Replacing the that slot in the example with:
```html
<template v-slot:item="row">
  <tr>
    <td v-for="value in Object.values(row.item)"
        @click="cell_click(value)"
    >
      {{ value }}
    </td>
  </tr>
</template>
```

And adding the method:
```python
def vue_cell_click(self, data):
        print(data)
```

Will fix the example notebook.

**Comment by gboaviagem** [comment]
That worked out great, @mariobuikhuizen. And changing `cell_click(value)` to `cell_click(row.item)` did the trick of passing to `vue_cell_click` the whole row, instead of only the cell value.

I found that if I try to enable the `show-select` property, it is overwritten by the v-slot and doesn't work (my code will need to be adjusted for this case), but it is beyond the scope of this issue. I'll close it since the solution was provided. Thanks!

**Comment by mkmitchell** [comment]
> That worked out great, @mariobuikhuizen. And changing `cell_click(value)` to `cell_click(row.item)` did the trick of passing to `vue_cell_click` the whole row, instead of only the cell value.
> 
> I found that if I try to enable the `show-select` property, it is overwritten by the v-slot and doesn't work (my code will need to be adjusted for this case), but it is beyond the scope of this issue. I'll close it since the solution was provided. Thanks!

It's been over a year but I was wondering if you had your test code still available.  I'm new to vue and have been playing with getting the PandasDataFrame in the example printing out via the click listener and can't seem to make it work.
