### ISSUE TITLE
Embedded content not displayed in ipyvuetify template

### ISSUE THREAD

**Issue by jcy204** [mariobuikhuizen/ipyvuetify#164]
Hi all,
I have been constructing a dashboard using ipyvuetify in voila-vuetify and so far the experience has been brilliant.

Within the dashboard are a selection of embedded Facebook posts. Here is an example of the code I am trying to embed into ipyvuetify: https://codepen.io/j_y204/pen/abWWzKw

I have converted this to ipyvuetify using the following code:

```python
from traitlets import Unicode
import ipyvuetify as v


post_template= '''

<head>
  <div id="fb-root"></div>
  <script async defer src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></script>
</head>

<v-card>
  <div class="fb-post"
data-href="https://www.facebook.com/20531316728/posts/10154009990506729/"
data-width="500"></div>
</v-card>

'''

class Select(v.VuetifyTemplate):
    template = Unicode(post_template).tag(sync=True)

Select()
```

Unfortunately, there is no output with this, am I approaching this the correct way?
My aim is to display a button which when pressed, a new post takes the spot in the widget.

I have tried an ipywidget.output `with output: clear_output() display(HTML(embeded_html)`  approach, and whilst this displays the first post, when a new post is loaded into the output, all outputs bizarrely disappear. 

I'd really appreciate any insight anyone may have into this - it has been the cause of a few days of hair-pulling and head-scratching!

Thanks,

James

**Comment by mariobuikhuizen** [comment]
Hi @jcy204 

This seems to work:
```python
from traitlets import Unicode
import ipyvuetify as v


post_template= '''
<template>
    <div>
        <div id="fb-root"></div>
        <component is="script" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></component>

        <v-card id="app">
            <div class="fb-post" data-href="https://www.facebook.com/20531316728/posts/10154009990506729/" data-width="500"></div>
        </v-card>
    </div>    
</template>
'''

class Select(v.VuetifyTemplate):
    template = Unicode(post_template).tag(sync=True)

Select()
```

Note that a template must have a single root node.

**Comment by jcy204** [comment]
Thanks for the response @mariobuikhuizen. That works - thanks! Sorry for the follow-up question, but is there a way to update the embedded post? I am trying the following code, however it just removes all outputs (as does an approach using ipywidgets.output) :

```python
from ipywidgets import  widgets, HBox
from traitlets import Unicode
import ipyvuetify as v


post_template= '''
<template>
    <div>
        <div id="fb-root"></div>
        <component is="script" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></component>

        <v-card id="app">
            <div class="fb-post" data-href="https://www.facebook.com/20531316728/posts/10154009990506729/" data-width="500"></div>
        </v-card>
    </div>    
</template>
'''

post_template_2 = '''
<template>
    <div>
        <div id="fb-root"></div>
        <component is="script" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></component>

        <v-card id="app">
            <div class="fb-post" data-href="https://www.facebook.com/facebookappUK/posts/10159779533841654" data-width="500"></div>
        </v-card>
    </div>    
</template>'''


class Select(v.VuetifyTemplate):
    template = Unicode(post_template).tag(sync=True)

embedded_post = Select()



def on_press(*args):
    embedded_post.template = post_template_2

btn = widgets.Button(description='Press')
btn.on_click(on_press)

HBox([btn,embedded_post])
```

**Comment by mariobuikhuizen** [comment]
The template isn't supposed to change. You can make a traitlet for the post URL and use that in the template:
`<div class="fb-post" :data-href="my_post_url" data-width="500"></div>` (see: https://ipyvuetify.readthedocs.io/en/latest/template_usage.html)

Also, something I noticed (in the notebook) was that the script has to be loaded once. If it's loaded a second time the post wouldn't show anymore. So I would put the loading of the script in a separate widget that's only on the page once.

**Comment by mariobuikhuizen** [comment]
Hmm.. that doesn't seem to work with the facebook framework.

**Comment by mariobuikhuizen** [comment]
Ok, a bit out of scope for ipyvuetify, but I've got it working:
```python
import traitlets
import ipyvuetify as v

class Select(v.VuetifyTemplate):
    my_post_url = traitlets.Unicode('https://www.facebook.com/20531316728/posts/10154009990506729/').tag(sync=True)
    
    @traitlets.default('template')
    def _template(self):
        return '''
        <template>
            <div>
                <div id="fb-root"></div>
                <component is="script" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></component>

                <v-card id="app">
                    <div class="fb-post" :data-href="my_post_url" data-width="500"></div>
                </v-card>
            </div>    
        </template>
        <script>
            modules.export = {
                mounted() {
                    setTimeout(FB.XFBML.parse);
                },
                watch: {
                    my_post_url() {
                        setTimeout(FB.XFBML.parse());
                    }
                }
            }
        </script>
        '''

select = Select()
select
```

To change te post:
```python
select.my_post_url = 'https://www.facebook.com/facebookappUK/posts/10159779533841654'
```

**Comment by jcy204** [comment]
Wow - honestly thank you so much for spending the time doing this, I really appreciate it and it works perfectly!!!

**Comment by jcy204** [comment]
Wow @mariobuikhuizen - honestly thank you so much for spending the time doing this, I really appreciate it and it works perfectly!!!
