### ISSUE TITLE
Creating ipyvuetify's widget break embed mode

### ISSUE THREAD

**Issue by hainm** [mariobuikhuizen/ipyvuetify#17]
hi, 
Please see the below example
<img width="1211" alt="Screen Shot 2019-06-30 at 12 24 30 PM" src="https://user-images.githubusercontent.com/4451957/60399427-0a994e00-9b32-11e9-8798-3dd67c3428bd.png">

If I click "Widgets" -> "Embed Widgets" to get the html code and display it, there will be nothing. The JS console says: 
<img width="283" alt="Screen Shot 2019-06-30 at 12 25 54 PM" src="https://user-images.githubusercontent.com/4451957/60399435-3a485600-9b32-11e9-9b56-772d0d8951ed.png">

I guess this is because you have not published v0.1.0 yet? (please see the attached html)
[vue.html.txt](https://github.com/mariobuikhuizen/ipyvuetify/files/3343082/vue.html.txt)

**Comment by mariobuikhuizen** [comment]
It wasn't published on NPM yet. It's also time to release it as v0.1.0, which is now published on NPM.
