### ISSUE TITLE
get value select from select

### ISSUE THREAD

**Issue by fcarpentey75012** [mariobuikhuizen/ipyvuetify#171]
It's a very simple question, but I didn't find the solution. I use this code and I would like to get the value from Select widget. For example, if I click on "Apple" I would like to get this value in an feature.

What is the workflow to get the value from the widget in ipyvuetify ?

```
import ipyvuetify as v

def on_click(widget, event, data):
        print(widget, event, data)

a = v.Col(cols=4, children=[
            v.Select(label='Functions', items=['Apple', 'Pear', 'Cherry'], outlined=True)
        ])

a.on_event('click', on_click)
a
```

**Comment by mariobuikhuizen** [comment]
You can find the documentation on that here: https://ipyvuetify.readthedocs.io/en/latest/usage.html#reading-the-value

**Comment by fcarpentey75012** [comment]
Hello, thank you ! i don't know if you have an solution but in my process a would link to link the selection of value in the select with an call to another Widget. But I must to click two time to see the new value, I try to modify "click" by another but it's not work.

```
def on_click(widget, event, data, *args):
    print(f"{select_function.v_model}")# 

select_function = v.Select(
            v_model='',
            label='Functions',
            items=['A', 'B'])

select_function.on_event('click', on_click)
select_function
```

Do you have an idea?

**Comment by mariobuikhuizen** [comment]
The event that is fired on a change of the select is `change` not `click`. You can find more on the underlying Vuetify components on: https://v2.vuetifyjs.com/en/components/selects/
E.g.:
<img width="557" alt="Screenshot 2021-08-14 at 19 41 13" src="https://user-images.githubusercontent.com/46192475/129455780-024a8193-7477-4b8f-b5af-aa95b84bd2b3.png">

**Comment by fcarpentey75012** [comment]
Thank you, very interesting like documentation. So i can keep the on_event methods and replace "click" by "change" in my script ? Like this : 

```
import ipyvuetify as v
import ipywidgets as widgets

def on_click(widget, event, data):
    print(widget, event, data)

a = v.Col(cols=4, children=[
            v.Select(
                v_model='',
                label='Functions', items=['Apple', 'Pear', 'Cherry'], outlined=False)
        ])

a.on_event('change', on_click)
a
```

**Comment by fcarpentey75012** [comment]
Hello, thank you ! Perfect documentation it's done for me. 

```
import ipyvuetify as v
import ipywidgets as widgets
from ipywidgets import Layout

def on_click(widget, event, data):
    print(a.v_model)
    print(widget, event, data)

a = v.Select(
                v_model='',
                label='Functions', items=['Apple', 'Pear', 'Cherry'], outlined=False)

a.on_event('change', on_click)
a
```
