### ISSUE TITLE
vuetify Switch on_event

### ISSUE THREAD

**Issue by samiit** [mariobuikhuizen/ipyvuetify#187]
Hi

I would like to trigger a function when the value of a `Switch` is changed. Something like:

```
import ipyvuetify as v
s = v.Switch(v_model = False, label="Labels")
def displayNode(widget, event, data):
    displayPlot.fire_event("click", None)

s.on_event("click", displayNode)
```

The problem is with "click". What else should I use in order that the switch's change of value is captured?

Thanks,

Sam

**Comment by mariobuikhuizen** [comment]
The state of the switch is kept in `v_model`, which can be observer with `observe` of ipywidgets (see https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html#Traitlet-events):
```python
import ipyvuetify as v
s = v.Switch(v_model = False, label="Labels")
def displayNode(change):
    print(f'handle switch state here, switch on: {change["new"]}')

s.observe(displayNode, names='v_model')
s
```

**Comment by samiit** [comment]
Thanks @mariobuikhuizen  for pointing out to the right resource and for your example. It works now!

Sam
