### ISSUE TITLE
TextField not passing attributes to <input> element

### ISSUE THREAD

**Issue by jimustafa** [mariobuikhuizen/ipyvuetify#188]
When passing the `min`, `max`, and `step` attributes to `TextField`, they do not seem to be applied to the associated `<input>` element. Is this possible?

**Comment by mariobuikhuizen** [comment]
A Vuetify `TextField` doesn't have those attributes, see https://vuetifyjs.com/en/api/v-text-field/#props

You can either use a `Slider` or make a component with these attributes with https://ipyvuetify.readthedocs.io/en/latest/template_usage.html.

**Comment by jimustafa** [comment]
Thanks @mariobuikhuizen. While `v-text-field` does not seem to have those properties, it is possible to pass them through to the `<input>` using a template. Is this what you were suggesting?

```python
class MyNumberField(v.VuetifyTemplate):
    label = traitlets.Unicode().tag(sync=True)
    value = traitlets.Float(default_value=0).tag(sync=True)
    min = traitlets.Float(default_value=0).tag(sync=True)
    max = traitlets.Float(default_value=1).tag(sync=True)
    step = traitlets.Float(default_value=0.1).tag(sync=True)

    @traitlets.default('template')
    def _template(self):
        return '''
          <v-text-field
            :label="label"
            type="number"
            v-model="value"
            :min="min" :max="max" :step="step"
          ></v-text-field>
        '''
```

**Comment by jimustafa** [comment]
A follow-up question... Is it possible to use `on_event` for a templated component? Taking again the example from above, with an added `vue_input` method, I tried `on_event('input', ...)` but got `AttributeError: 'MyNumberField' object has no attribute 'on_event'`. Maybe there is a different way of doing this.

```python
class MyNumberField(v.VuetifyTemplate):
    label = traitlets.Unicode().tag(sync=True)
    value = traitlets.Float(default_value=0).tag(sync=True)
    min = traitlets.Float(default_value=0).tag(sync=True)
    max = traitlets.Float(default_value=1).tag(sync=True)
    step = traitlets.Float(default_value=1).tag(sync=True)

    @traitlets.default('template')
    def _template(self):
        return '''
          <v-text-field
            :label="label"
            type="number"
            v-model="value"
            :min="min" :max="max" :step="step"
            @input="input()"
          ></v-text-field>
        '''

    def vue_input(self):
        pass
```

**Comment by mariobuikhuizen** [comment]
No I didn't mean that, since I thought v-text-field didn't have those props :). But the html attributes are passed on to the input I see now, so this can also be achieved with the object API by setting HTML attributes: `v.TextField(type='number', attributes={'min': 0, 'max': 1, 'step': 0.1})`. I should update the docs to describe this use: https://ipyvuetify.readthedocs.io/en/latest/usage.html?highlight=attributes#regular-html-tags

The events indeed work a bit different in the template API, the `on_event` is not available and should be handled as you showed. A small change for getting the value of an event:
```python
class MyNumberField(v.VuetifyTemplate):
    label = traitlets.Unicode().tag(sync=True)
    value = traitlets.Unicode(default_value='0').tag(sync=True)
    min = traitlets.Float(default_value=0).tag(sync=True)
    max = traitlets.Float(default_value=1).tag(sync=True)
    step = traitlets.Float(default_value=1).tag(sync=True)

    @traitlets.default('template')
    def _template(self):
        return '''
          <v-text-field
            :label="label"
            type="number"
            v-model="value"
            :min="min" :max="max" :step="step"
            @input="input($event)"
          ></v-text-field>
        '''

    def vue_input(self, data):
        print(data)
```

**Comment by jimustafa** [comment]
Using the `attributes` keyword works as advertised. Thanks!
