### ISSUE TITLE
looking for an ipyvuetify example of a dense toolbar

### ISSUE THREAD

**Issue by joseberlines** [mariobuikhuizen/ipyvuetify#201]
Hi 

I am simply looking for an examply in ipyvuetify python example for a dense toolbar as in https://vuetifyjs.com/en/components/toolbars/#dense-toolbars

where the menu includes buttons and an input fields

thanks for the help

**Comment by mariobuikhuizen** [comment]
What's the problem you run into with this specific use case? What have you already tried?

**Comment by joseberlines** [comment]
The problem was that in the Vuetify page there was no code example of how to "fill in the menu". I posted this question later on in SO and I got this answer which is super great:
https://stackoverflow.com/questions/70416286/python-how-to-add-items-to-a-menu-of-an-ipyvuetify-toolbar
