### ISSUE TITLE
Is it possible to modify an expansion panel to make it fold horizontally instead of vertically?

### ISSUE THREAD

**Issue by joseberlines** [mariobuikhuizen/ipyvuetify#202]
The question says it all.

Here the code for simple vertical expansion panels.

vepc1 = v.ExpansionPanel(children=[
    v.ExpansionPanelHeader(children=['item1']),
    v.ExpansionPanelContent(children=['First Text'])])

vepc2 = v.ExpansionPanel(children=[
    v.ExpansionPanelHeader(children=['item2']),
    v.ExpansionPanelContent(children=['Second Text'])])

vep = v.ExpansionPanels(children=[vepc1, vepc2])
vl = v.Layout(class_='pa-4', children=[vep])
vl

What I am looking for is a way to create a sort of Tacle of contents on the left of the page that can be folded away laterally.

thanks

**Comment by mariobuikhuizen** [comment]
Would a navigation drawer work for you? https://vuetifyjs.com/en/components/navigation-drawers/#bottom-drawer

**Comment by joseberlines** [comment]
Yes Mario, that would do it. thanks
