### ISSUE TITLE
Is there a way to add extra keywords to a ipyvuetify object ? 

### ISSUE THREAD

**Issue by 12rambau** [mariobuikhuizen/ipyvuetify#204]
I have a specific use case in mind but that could also bo useful for people using the data-* attribute as well. 

I want to rceate a download btn for one of my application. I have the absolute url of the file, and I have the right to access it. According to the web (https://stackoverflow.com/questions/65047651/vue-download-file-from-link-href-and-vuetify-v-btn) a simple trick is to add the `download` attribute to the html element which in my case would be something like: 

``` html
<v-btn 
   class="ma-2" 
   outlined 
   href="file.pdf"
   download>
       Download PDF
</v-btn>
```

To reproduce this behaviour with ipyvuetfy I tried: 

```py 
v.Btn(class_="ma-2", outlined=True, href="file.pdf", download=True)
```

But the `download` attribute is not added to the `<a>` tag when the template is rendered. 

Is there a trick to add custom attributes to a tag ?

**Comment by mariobuikhuizen** [comment]
Yes, this can be done with `attributes`:
```python
v.Btn(class_="ma-2", outlined=True, href="file.pdf", attributes={'download': True})
```

**Comment by 12rambau** [comment]
thanks for your quick answer! 
Is it something that should be documented? I didn't find it in the **attribute** section of ipyvuetify doc and it's obviously not documented in the vuetify one

**Comment by mariobuikhuizen** [comment]
Yeah, it should. It's documented here: https://ipyvuetify.readthedocs.io/en/latest/usage.html#regular-html-tags, but it's not clear it also applies to all ipyvuetify widgets.
