### ISSUE TITLE
Active tooltips stick if their cell is reloaded

### ISSUE THREAD

**Issue by JazzTap** [mariobuikhuizen/ipyvuetify#24]
This is a problem only ever caused by haste, and probably a subset of orphaned callbacks due to live UI editing in general.

Reloading a cell with shift-enter orphans any active tooltip generated by it, which subsequently requires DOM introspection to remove.

Reproducible using the 'tooltip' button in examples notebook.

![](https://i.imgur.com/afNO2Js.png)

**Comment by mariobuikhuizen** [comment]
Thanks for reporting this issue.
