### ISSUE TITLE
How to display an image?

### ISSUE THREAD

**Issue by marketneutral** [mariobuikhuizen/ipyvuetify#26]
How would I simply display an image? I tried playing with `v.Img(...)` with no luck. Thank you.

**Comment by marketneutral** [comment]
Answering my own question...

```
v.Img(src ='https://picsum.photos/id/11/500/300' )
```

works!

**Comment by marketneutral** [comment]
Sorry, I closed this too fast 😞. I was hoping to be able to display a `seaborn` plot by `plt.savefig('/tmp/myfig.png')` and then `v.Img(src ='file:///tmp/myfig.png')` but this returns nothing. Does Vue have access to the local filesystem? How would I load an image from the file system?

**Comment by mariobuikhuizen** [comment]
Ipyvuetify Img does not have access to the local filesystem. You can use the image component of ipywidgets instead.

**Comment by marketneutral** [comment]
Thank you! This works very well. Example,

```python
import ipyvuetify as v
import ipywidgets as widgets
import matplotlib.pyplot as plt
import seaborn as sns

sns.axes_style("darkgrid")
sns.set(rc={'figure.facecolor':'#EAEAF2'})
fmri = sns.load_dataset("fmri")
fig = sns.lineplot(x="timepoint", y="signal", hue="region", style="event", data=fmri)
plt.savefig('/tmp/output.jpg', format='jpg');

file = open("/tmp/output.jpg", "rb")
image = file.read()
img = widgets.Image(value=image, format='jpg')

vepc1 = v.ExpansionPanelContent(children=[
    v.Html(tag='div', slot='header', children=['Plot Header']),
    v.Card(children=[
        v.CardText(children=[img])])])
vep = v.ExpansionPanel(children=[vepc1])
vl = v.Layout(children=[vep])
vl
```
![image](https://user-images.githubusercontent.com/16124573/62463926-52c31600-b759-11e9-9633-b8c9a162d0ce.png)

It's not as fancy as the `bqplot` stuff with interactions, but still works well and is reactive (plot will scale down when the window is resized smaller).

**Comment by maartenbreddels** [comment]
Since seaborn uses matplotlib, you can also use ipympl https://github.com/matplotlib/jupyter-matplotlib/ to get interactive plots
