### ISSUE TITLE
Toolbar spacing below

### ISSUE THREAD

**Issue by marketneutral** [mariobuikhuizen/ipyvuetify#27]
I have a dashboard skeleton and am having a problem with the toolbar. I like the `app=True` but the component directly below is partially hidden by it. What is the best practice on how to move down that component? Is it right to use a `Card` inside a `Container`? I'm also curious why the `Container` background is not flush with the left and right edges of the window.

```python
my_dashboard_name = 'My Dashboard App'
button_list = {
    'link1': 'http://www.apple.com',
    'link2': 'http://www.google.com',
}
lst = [
    v.Btn(children=[name], flat=True, href=link, target='_blank')
    for name, link in button_list.items()
]

# This creates the application nav bar. It doesn't display in the notebook.
toolbar = v.Toolbar(
    children=[
        v.ToolbarSideIcon(),
        v.ToolbarTitle(children=[my_dashboard_name]),
        v.Spacer(), # Fills empty space
        v.ToolbarItems(children=lst)
    ],
    app=True,  # If true, the other widgets float under on scroll
)

vepc1 = v.ExpansionPanelContent(children=[
    v.Html(tag='div', slot='header', children=['item1']),
    v.Card(children=[
        v.CardText(children=['Some Text'])])])

vepc2 = v.ExpansionPanelContent(children=[
    v.Html(tag='div', slot='header', children=['item2']),
    v.Card(children=[
        v.CardText(children=['Second Text'])])])

vep = v.ExpansionPanel(children=[vepc1, vepc2])
vl = v.Container(children=[v.Card(children=[toolbar, vep], elevation=10)])
vl
```

![image](https://user-images.githubusercontent.com/16124573/62486171-84090980-b78c-11e9-82c3-76f77e29db87.png)

**Comment by marketneutral** [comment]
I figured out the first question. To create space,  `v1 = v.Container(mt_5=True...`; the `mt_5` parameter maps to "margin", "top", 5, as in `{property}{direction}-{size}` here in the [Vuetify docs](https://v15.vuetifyjs.com/en/framework/spacing).

I'm still confused as to why the Container is not flush on left and right though.

**Comment by mariobuikhuizen** [comment]
The extra padding is caused by notebook css styles which are still loaded in voila.

**Comment by marketneutral** [comment]
I see. Thank you.

If I point my browser to `localhost:8866/voila/static/theme-light.css` I can see the theme. I believe this is the offending line:

```css
  /* Notebook specific styles */

  --jp-notebook-padding: 10px;
```
I can't seem to find this file though on the file system. When I start voila I see `[Voila] Serving static files from /opt/conda/lib/python3.6/site-packages/voila/static`, but this directory does not contain the file when I cd into it.

**Comment by mariobuikhuizen** [comment]
I think the Voila team can answer this question better than I can.

**Comment by maartenbreddels** [comment]
You can create a custom template, and the default template is in $prefix/share/jupyter/voila/default (Which includes the static directory)

**Comment by maartenbreddels** [comment]
I'm assuming this issue is resolved, feel free to re-open if you disagree.
