### ISSUE TITLE
Properties do not support modifiers?

### ISSUE THREAD

**Issue by nmearl** [mariobuikhuizen/ipyvuetify#28]
Some vuetify components have properties that allow modifiers, see the [`mini-variant` property](https://v15.vuetifyjs.com/en/components/navigation-drawers#api) here, which allows a `sync` modifier. This doesn't seem to be supported currently through the generated bindings.

**Comment by mariobuikhuizen** [comment]
This is indeed not supported. The sync modifier is syntactic sugar for binding an update event. We can accomplish the same using:
```python
drawer = v.NavigationDrawer(..., mini_variant=True, ...)

def update_mini(widget, event, data):
    drawer.mini_variant = data

drawer.on_event('update:miniVariant', update_mini)
```

**Comment by nmearl** [comment]
Ah, yes, yes. I thought I could work around it by handling the bindings myself, but it wasn't working -- the `update:miniVariant` is what I was missing! Thanks, @mariobuikhuizen.
