### ISSUE TITLE
Navigation Drawer open and close

### ISSUE THREAD

**Issue by brechmos-stsci** [mariobuikhuizen/ipyvuetify#3]
I am trying to create a NavigationDrawer but can't see how to show/hide it (I am in a jupyter notebook but don't think that is the issue).
 
 ```
def on_click(widget, event, data):
    pass  # (?)

vnd = v.NavigationDrawer(right=True, children=[v.Btn(color='primary', children=['Drawer button'])])

show_drawer = v.Btn(color='primary', children=['Open'])
show_drawer.on_event('click', on_click)

v.Layout(children=[show_drawer, vnd])  # (?)
```

I see some examples of doing this in Vuetify, but I am not sure how the mapping works of the display method to ipyvuetify (e.g., `https://codepen.io/thiagoaos/pen/KygpxV`)

There is a v_model which I assume maps to the v-model, but it says "!!disabled!!" so not sure if that is working in ipyvuetify?

Any guidance would be appreciated.

**Comment by nmearl** [comment]
You can use either the `v_model` attribute, or the `value` attribute:

```
nav = v.NavigationDrawer(value=False, app=True)

def on_click(*args, **kwargs):
    nav.value = not nav.value
    
btn = v.Btn(children=["click"])

btn.on_event('click', on_click)
```

**Comment by brechmos-stsci** [comment]
Awesome...

**Comment by mariobuikhuizen** [comment]
The referenced codepen uses a very old version of vuetify. These examples are up to date: https://vuetifyjs.com/en/components/navigation-drawers

I've adapted your example to the following:
```
def on_click(widget, event, data):
   vnd.v_model = not vnd.v_model

drawer_button = v.Btn(color='primary', children=['Drawer button'])
drawer_button.on_event('click', on_click)

vnd = v.NavigationDrawer(v_model=False, absolute=True, right=True, children=[
    drawer_button
])

show_drawer = v.Btn(color='primary', children=['Toggle'])
show_drawer.on_event('click', on_click)

v.Layout(children=[vnd, show_drawer]) 
```

The v_model's initial value '!!disabled!!' means it is not initialized. We can't use null for this, because that's a valid value. Come to think of it !!un_initialized!! is probably more clear.

**Comment by brechmos-stsci** [comment]
:)  Disabled confused me. lol
