### ISSUE TITLE
ExpansionPanel header

### ISSUE THREAD

**Issue by brechmos-stsci** [mariobuikhuizen/ipyvuetify#4]
I am trying to create an `ExpansionPanel`:

```
vepc1 = v.ExpansionPanelContent(children=[v.Card(children=[v.CardText(children=['here is the text'])])])

expanel = v.ExpansionPanel(children=[vepc1])
expanel
```

which is sort of based on the code at `https://vuetifyjs.com/en/components/expansion-panels`:
```
  <v-expansion-panel>
    <v-expansion-panel-content
      v-for="(item,i) in 5"
      :key="i"
    >
      <template v-slot:header>
        <div>Item</div>
      </template>
      <v-card>
        <v-card-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</v-card-text>
      </v-card>
    </v-expansion-panel-content>
  </v-expansion-panel>
```

But, we can't seem to figure out how to add the header (i.e., `Item`) that is defined in the `<template v-slot:header>`.  We looked at the `slot=` parameter of `v.ExpansionPanelContent` but passing a text parameter to it doesn't seem to render.  

So, some guidance on the ExpansionPanel would be great. Thanks!

**Comment by mariobuikhuizen** [comment]
v-slot:header is new slot syntax of vue which is not yet supported. You can use slot="header" instead. With this syntax the template tag is not necessary.

```
vepc1 = v.ExpansionPanelContent(children=[
    v.Html(tag='div', slot='header', children=['header']),
    v.Card(children=[
        v.CardText(children=['here is the text'])])])

expanel = v.ExpansionPanel(children=[vepc1,vepc1])
expanel
```

**Comment by brechmos-stsci** [comment]
With the example above and the example added in https://github.com/mariobuikhuizen/ipyvuetify/pull/5, there is not more needed on this issue (so I am going to close it, only because I opened it :) ).
