### ISSUE TITLE
Dynamic Dialog open

### ISSUE THREAD

**Issue by yarmenti** [mariobuikhuizen/ipyvuetify#43]
Hello,

I'm currently having issues to open a Dialog after the execution of a function.
I saw in your `Examples.ipynb` that you are specifying the opener as being a button, itself embedded in the `v_slots` parameter of the Dialog.

I'm trying, when clicking to a button, to execute a given function using `.on_event("click", a_func)` and inside `a_func` opening the Dialog. Could you tell me how to do so?

Thanks,

Yannick

**Comment by mariobuikhuizen** [comment]
You can use v_model for that:
```python
import ipyvuetify as v

dialog = v.Dialog(width='500', v_model=False, children=[
        v.Card(children=[
            v.CardTitle(class_='headline gray lighten-2', primary_title=True, children=[
                "Lorem ipsum"
            ]),
            v.CardText(children=[
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt'
            ])
        ])
    ])

def open_dialog(*args):
    dialog.v_model = True
    
btn = v.Btn(children=['open dialog'])
btn.on_event('click', open_dialog)

v.Container(children=[dialog, btn])
```

**Comment by yarmenti** [comment]
Thank you!
Actually I was confused using either JS or Python boolean for v_model.

Perfect!!!!

**Comment by maartenbreddels** [comment]
Were you not seeing an error, were you using jupyter lab? otherwise, you can use the output widget to capture errors. https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html

**Comment by yarmenti** [comment]
No, actually as it is a "not-so-light" dashboard, I was refreshing my voila app ^^
