### ISSUE TITLE
Updating properties of objects not causing refresh

### ISSUE THREAD

**Issue by jy247** [mariobuikhuizen/ipyvuetify#44]
Thanks for your wonderful library.

I am trying to build a template, where-by an object is displayed inside a form.  When I update a property of the object it does not cause a refresh of the content.  

I can imagine you need to trigger a refresh somehow to let the javascript know that the properties of the object have changed, is this possible?  Or am I doing something wrong in the setup?

In the example below, the field 'lala' will update immediately on running the code, the field 'legend' will not.

thanks again

Jack

i.e.

template:                     

```
<template>
  <div>
      <v-text-field
      v-model="lala"
    ></v-text-field>
    <v-text-field
      v-model="items.Legend"
    ></v-text-field>
  </div>         
</template>
```

```
test_dic = { 'Legend':'this is old'}

import ipyvuetify as v
import ipywidgets as widgets

from traitlets import (Unicode, List, Bool, Any)

filename = r'H:\web\vue\jack1\src\components\CV.vue'

with open(filename, "r") as f:
    contents = f.read()
    
class MyApp(v.VuetifyTemplate):
    lala = Unicode('this is old').tag(sync=True)
    items = Any(test_dic).tag(sync=True)
    template = Unicode(contents).tag(sync=True)
    
app = MyApp()
app

app.items['Legend'] = 'this is new legend'
app.items = app.items
app.lala = 'this is new lala'

```

**Comment by jy247** [comment]
I see that it is not synced in either direction in this case, i.e. if I update the text box the value in the dictionary is not changed.

If I am displaying the value somewhere else in the form, however, that will be simultaneously updated as I type.

**Comment by mariobuikhuizen** [comment]
It's nice to hear you like it!

Traitlets only detect changes on assignment of a new value, not on modification of the content. Also, the assignment of the same value goes undetected.

In the front-end changes to the content are also not detected and synced back.

This is a limitation of Traitlets and ipywidgets.

It's possible to add traitlets at runtime with self.add_traits(). Maybe you can use this to implement your use case.

**Comment by jy247** [comment]
Thanks for swift reply, i did try reassigning the whole object as above:

app.items = app.items

with no effect, is there anything like that which could trigger an update on the whole object?

Just tried add_traits and it works, which is awesome, will combine that with building the template in code with some custom tokens.

I had been playing with trying to amend the class using this before instantiation

```
tokens_dic = {
    '<$variable>' : ('variable', lambda index: Unicode(letters[index]).tag(sync=True)),
    '<$expression>' : ('expression', lambda index: Unicode('').tag(sync=True)),
    '<$legend>' : ('legend', lambda index: Unicode('').tag(sync=True)),
    '<$leftaxis>' : ('leftaxis', lambda index: Bool(True).tag(sync=True)),
}

def amend_class(num_rows):
    for i in range(num_rows):
        for key, value in tokens_dic.items():
            exec("MyApp.{}{} = '{}'".format(value[0], i, value[1](i)))

```
but there must be some magic happening that I don't understand because these class properties don't seem to be available as traits.

**Comment by mariobuikhuizen** [comment]
> Thanks for swift reply, i did try reassigning the whole object as above:
>
> app.items = app.items

Assigning the same value is not detected as change.

> but there must be some magic happening that I don't understand because these class properties don't seem to be available as traits.

Traitlets have to be attributes of HasTraits sub classes (and then some magic is indeed being applied :wink:). See https://traitlets.readthedocs.io/en/stable/using_traitlets.html

**Comment by jy247** [comment]
Story checks out,  In the below code I can programmatically update in a way that refreshes the UI.

If I switch the position of the update from Test3, to Test2 it will not cause a refresh.  It also won't work without the deepcopy.

`import copy
#app.items[0]['Expression'] = 'Test2'
new_items = [copy.deepcopy(a) for a in app.items]
new_items[0]['Expression'] = 'Test3'
app.items = new_items`

I can wrap this operation to make it transparent so it might be a cleaner way of working for me than the above.  It will require manually catching the update events from the javascript though...
