### ISSUE TITLE
Capturing events when using templates

### ISSUE THREAD

**Issue by jy247** [mariobuikhuizen/ipyvuetify#46]
Hi, I am trying to capture update events on a DOM created from a template.

So in a simple example

```
<v-btn @click='test_update()'/>
```
I assume this will look for a javascript function.  Is there a way to either

-  Specify a python update function here
- Include a javascript function, preferably one that will then call a python function.

If neither of these are possible, is there a way to grab an item by id from the app object in python, so that I can add events to it after it has been created from the template?

Many thanks again and happy new year!

Jack

**Comment by jy247** [comment]
Apologies, found this after reviewing the examples.  Works great when i rename the function vue_function_name().

**Comment by maartenbreddels** [comment]
Great to hear you solved it yourself!

(from mobile phone)
