### ISSUE TITLE
Placing BQPlot in IPYVuetify template 

### ISSUE THREAD

**Issue by jy247** [mariobuikhuizen/ipyvuetify#47]
Hi,

I am creating a dashboard using Voila, BQplot and IPYVuetify. At the moment I am just creating the figure(s) so they are above the controls (which are defined in a template), but it would be great if they could be embedded in the HTML template definition somehow.

Is this currently possible? Are there any examples you could share?

Many thanks again

Jack

**Comment by Jul3k** [comment]
Does the the components attribute help you?
https://github.com/mariobuikhuizen/ipyvuetify/issues/29

**Comment by jy247** [comment]
Thanks very much Jul3k, this worked well.

I had to put a fixed pixel size on the layout object containing the BQPlot, in order to spread it out a bit, but apart from that it just worked!

**Comment by jy247** [comment]
In addition to the above, I found that by NOT wrapping the BWPlot figure in a layout component at all, I was able to get the chart to take up the full available width.
