### ISSUE TITLE
'fill-height' attribute missing for new grid layout components

### ISSUE THREAD

**Issue by Jul3k** [mariobuikhuizen/ipyvuetify#49]
I tried to work with the new grid layout v2 (https://vuetifyjs.com/en/components/grids) and realized that the `'fill-height` attribute in not parsed in some cases as it should (Container, Row, Col).

`content_main = v.Container(_metadata={'mount_id': 'content-main'}, fill_height=True, ...)`

it is parsed for the old style Layout component:
`content_main = v.Layout(_metadata={'mount_id': 'content-main'}, fill_height=True,  ...)`

Edit:
I added `fill_height = Bool(None, allow_none=True).tag(sync=True)` to the Container class and now it works but I guess the code is autogenerated somewhere.

**Comment by nmearl** [comment]
`fill-height` isn't a property (so you wouldn't be able to pass it in as an argument when you instantiate the `Container`/``Layout` class); it's a css class. You may want to try

```python
content_main = v.Container(_metadata={'mount_id': 'content-main'}, class_="fill-height", ...)
```

**Comment by Jul3k** [comment]
Sounds right to me. Thanks for the help! This is closed then
