### ISSUE TITLE
Horizontal reducing panel (Ipyvuetify) 

### ISSUE THREAD

**Issue by AnnaHanae** [mariobuikhuizen/ipyvuetify#52]
Hello,  is there a component for reducing **horizontal** space with large amounts of information with ipyvuetify ? 

<img width="140" alt="horizontalPannel" src="https://user-images.githubusercontent.com/10080500/76607788-dc6b6b00-6514-11ea-8aac-afc748eb9ac1.PNG">

thanks in advance.

**Comment by mariobuikhuizen** [comment]
Yes, there is NavigationDrawer for that.

Taken from the examples and modified to look more like your use case:
```python
def on_click(widget, event, data):
   vnd.v_model = not vnd.v_model

drawer_button = v.Btn(color='primary', children=['Close drawer'])
drawer_button.on_event('click', on_click)

vnd = v.NavigationDrawer(v_model=False, absolute=True, children=[
    drawer_button, v.Select(label='select1'), v.Select(label='select2')
])

show_drawer = v.Btn(color='primary', style_='margin-bottom: 200px', children=['Open drawer'])
show_drawer.on_event('click', on_click)

v.Layout(children=[vnd, show_drawer]) 
```
![navdrawer](https://user-images.githubusercontent.com/46192475/76746964-a62e2580-6778-11ea-8bb6-6eb18e821e8c.gif)

It just needs a nice icon button at the right position.

**Comment by AnnaHanae** [comment]
> Yes, there is NavigationDrawer for that.
> 
> Taken from the examples and modified to look more like your use case:
> 
> ```python
> def on_click(widget, event, data):
>    vnd.v_model = not vnd.v_model
> 
> drawer_button = v.Btn(color='primary', children=['Close drawer'])
> drawer_button.on_event('click', on_click)
> 
> vnd = v.NavigationDrawer(v_model=False, absolute=True, children=[
>     drawer_button, v.Select(label='select1'), v.Select(label='select2')
> ])
> 
> show_drawer = v.Btn(color='primary', style_='margin-bottom: 200px', children=['Open drawer'])
> show_drawer.on_event('click', on_click)
> 
> v.Layout(children=[vnd, show_drawer]) 
> ```
> 
> ![navdrawer](https://user-images.githubusercontent.com/46192475/76746964-a62e2580-6778-11ea-8bb6-6eb18e821e8c.gif)
> 
> It just needs a nice icon button at the right position.

that's exactly what i'm looking for. Thank you !
