### ISSUE TITLE
'OverflowBtn' object has no attribute '_event_handlers_map'

### ISSUE THREAD

**Issue by javerbukh** [mariobuikhuizen/ipyvuetify#6]
Hi,
I am using the OverflowBtn and am trying to create a click event for it, but I am getting the following error:

```
x = v.OverflowBtn(label="Slit", items=["test", "hi"])
x.on_event('click', on_click)

AttributeError: 'OverflowBtn' object has no attribute '_event_handlers_map'
```

Is there a plan to add event_handler to OverflowBtn?

**Comment by mariobuikhuizen** [comment]
This should actually work. The following works on my machine:
```
import ipyvuetify as v

status = v.Chip(children=["-"])

def on_click(event, widget, data):
    status.children=[f'click y: {data["y"]}']
        
x = v.OverflowBtn(label="Slit", v_model=None, items=["test", "hi"])
x.on_event('click', on_click)

v.Layout(children=[x, status])
```

If you're interested in the change of the selected value, you can use:
```
import ipyvuetify as v

status2 = v.Chip(children=["-"])

x2 = v.OverflowBtn(label="Slit", v_model=None, items=["test", "hi"])

def x2_change(v):
    status2.children=[f'selected value: {v.new}']

x2.observe(x2_change, names=['v_model'])

v.Layout(children=[x2, status2])
```

Note that `v_model` should be initialized (`None` in this case) before it can be observed.

**Comment by maartenbreddels** [comment]
Does this help debugging it:
![image](https://user-images.githubusercontent.com/1765949/58538991-ad3e7400-81f6-11e9-9192-fa36cdcde4f2.png)

So it seems the _metadata trait matters.

**Comment by mariobuikhuizen** [comment]
I can't reproduce the error @maartenbreddels:
<img width="1097" alt="Schermafbeelding 2019-05-29 om 09 53 52" src="https://user-images.githubusercontent.com/46192475/58539530-d3b0df00-81f7-11e9-96e9-9065f0371c8f.png">

**Comment by javerbukh** [comment]
@mariobuikhuizen That worked for me, thank you!

**Comment by maartenbreddels** [comment]
I basically get 'random' behavior depending on which argument I pass or not.
 * Python 3.6.7
 * traitlets 4.3.2
 * ipyvuetify master

**Comment by mariobuikhuizen** [comment]
I've just bumped in to the `object has no attribute '_event_handlers_map'` error myself. In this case it was caused by specifying a non existing trait, which doesn't display an error when creating the widget, but does when adding an event listener.
