### ISSUE TITLE
Qgrid replacement using ipyvuetify

### ISSUE THREAD

**Issue by DougRzz** [mariobuikhuizen/ipyvuetify#71]
Hi Mario,  

Here is my Vuetify table implementation for a Qgrid replacement with similar api.  Includes get_selected_df() and .get_selected_rows().  There is also a csv file downloadble link for selected rows.

What do you think?

At some point, I would like to add a csv file upload button too.

![image](https://user-images.githubusercontent.com/3510318/83779568-08b20600-a684-11ea-8d68-2a84eb7fa6cc.png)

```python
import pandas as pd
import traitlets
import ipyvuetify as v
import json

import ipywidgets as widgets
import base64


def df2download(htmlWidget, filename, df):
    """  Convert a pandas dataframe to a downloadaable link


    htmlWidget:  html ipywidget
    filename:  str,  Name of csv file
    df: pandas dataframe

    For example:
        htmlWidget = widgets.HTML(value = '')
        htmlWidget

        df2download(htmlWidget, 'selectedRows.csv', test.get_selected_df())

    """
    if isinstance(df, pd.DataFrame):
        payload = base64.b64encode(df.to_csv().encode()).decode()

        # Create and assign html to widget
        html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
        #     html = '<button type="button">Click Me!</button><download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
        htmlWidget.value = html.format(payload=payload, title= filename, filename=filename)
    else:
        htmlWidget.value = ''


class VuetifyTable_pandas_df(v.VuetifyTemplate):
    """
    Vuetify DataTable rendering of a pandas DataFrame with similar methods to QGrid
    
    Args:
        data (DataFrame) - the data to render
        title (str) - optional title
        multiple (Bool) - True (default) enables multiple line selection
        dense (Bool) - True (default) enables dense rendering of table



    Example:

        import pandas as pd

        iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
        test = VuetifyTable_pandas_df(df = iris)

        test.title = 'sdvsd'
        test.multiple = True
        test.dense = True

        def onChange_table(change,widget):
        #     print(change['new'])
            print(widget.value)

        test.observe(onChange_table,'value',test)

        test.get_selected_df()

        test.get_selected_rows()

    """
    
    headers = traitlets.List([]).tag(sync=True, allow_null=True)
    items = traitlets.List([]).tag(sync=True, allow_null=True)
    value = traitlets.List([]).tag(sync=True, allow_null=True)
    search = traitlets.Unicode('').tag(sync=True)
    title = traitlets.Unicode('').tag(sync=True)
    index_col = traitlets.Unicode('').tag(sync=True)
    multiple =  traitlets.Bool(False).tag(sync=True)
    dense =  traitlets.Bool(False).tag(sync=True)
    template = traitlets.Unicode('''
        <template>
          <v-card>
            <v-card-title>
              <span class="title font-weight-bold">{{ title }}</span>
              <v-spacer></v-spacer>
                <v-text-field
                    v-model="search"
                    append-icon="mdi-magnify"
                    label="Search ..."
                    single-line
                    hide-details
                ></v-text-field>
            </v-card-title>
            <v-data-table
                :headers="headers"
                :items="items"
                :search="search"
                :item-key="index_col"
                :show-select="multiple"
                :dense ="dense"
                v-model="value"
                
                
                :footer-props="{'items-per-page-options': [10, 25, 50, 250, 500, 1000, 10000]}"
            >
                <template v-slot:no-data>
                  <v-alert :value="true" color="error" icon="mdi-alert">
                    Sorry, nothing to display here :(
                  </v-alert>
                </template>
                <template v-slot:no-results>
                    <v-alert :value="true" color="error" icon="mdi-alert">
                      Your search for "{{ search }}" found no results.
                    </v-alert>
                </template>
                <template v-slot:items="rows">
                  <td v-for="(element, label, index) in rows.item"
                      @click=cell_click(element)
                      >
                    {{ element }}
                  </td>
                </template>
                


            </v-data-table>
          </v-card>
        </template>
        ''').tag(sync=True)
    
    def __init__(self, *args, df=pd.DataFrame(), title=None, multiple = True, dense = False, **kwargs):
        super().__init__(*args, **kwargs)
        df = df.reset_index()
        self.index_col = df.columns[0]
        headers = [{
              "text": col,
              "value": col
            } for col in df.columns]
        headers[0].update({'align': 'left', 'sortable': True})
        self.headers = headers
        self.items = json.loads(
            df.to_json(orient='records'))
        if title is not None:
            self.title = title

        self.dense = dense
        self.multiple = multiple

        self.htmlWidget = widgets.HTML(value='')
        self.observe(self.onChange_table)

        # Combine table and widgets
        self.widgets = v.Card(children=[widgets.VBox([self,
                                       v.Row(children=[v.Tooltip(
                                           bottom=True,
                                           v_slots=[{'name': 'activator', 'variable': 'tooltip', 'children':
                                               v.Btn(v_on='tooltip.on',
                                                     color='black',
                                                     class_='ma-3',
                                                     icon=True,
                                                     children=[v.Icon(centre=True,
                                                                      medium=True,
                                                                      children=['info'])]
                                                     )}],
                                           children=['Select rows and click on link to download a CSV file of the selected rows']
                                       ),
                                           self.htmlWidget],
                                           align="center",
                                           justify="left")
                                       ])
                         ])

    def get_selected_df(self):
        if len(self.value) > 0:
            newDict = {}
            for k in self.value[0].keys():
                newDict[k] = [dictionary[k] for dictionary in self.value]
            df = pd.DataFrame.from_dict(newDict)
            df = df.set_index('index')
            return df
        else:
            return []
    
    def get_selected_rows(self):
        return [dictionary['index'] for dictionary in self.value]

    def onChange_table(self, change):
        df2download(self.htmlWidget, 'selectedRows.csv', self.get_selected_df())

```

```python

import pandas as pd

iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
test = VuetifyTable_pandas_df(df = iris)

test.widgets
```

```python
test.title = 'sdvsd'
test.multiple = True
test.dense = True

# example function when table changes
def onChange_table(change,widget):
    print(widget.value)

test.observe(onChange_table,'value',test)

test.get_selected_df()

test.get_selected_rows()
```

**Comment by mariobuikhuizen** [comment]
Hi DougRzz,

This looks great! I didn't know one can use data URLs for file downloads, nice find!

**Comment by trbedwards** [comment]
> Hi Mario,
> 
> Here is my Vuetify table implementation for a Qgrid replacement with similar api. Includes get_selected_df() and .get_selected_rows(). There is also a csv file downloadble link for selected rows.
> 
> What do you think?
> 
> At some point, I would like to add a csv file upload button too.
> 
> ![image](https://user-images.githubusercontent.com/3510318/83779568-08b20600-a684-11ea-8d68-2a84eb7fa6cc.png)
> 
> ```python
> import pandas as pd
> import traitlets
> import ipyvuetify as v
> import json
> 
> import ipywidgets as widgets
> import base64
> 
> 
> def df2download(htmlWidget, filename, df):
>     """  Convert a pandas dataframe to a downloadaable link
> 
> 
>     htmlWidget:  html ipywidget
>     filename:  str,  Name of csv file
>     df: pandas dataframe
> 
>     For example:
>         htmlWidget = widgets.HTML(value = '')
>         htmlWidget
> 
>         df2download(htmlWidget, 'selectedRows.csv', test.get_selected_df())
> 
>     """
>     if isinstance(df, pd.DataFrame):
>         payload = base64.b64encode(df.to_csv().encode()).decode()
> 
>         # Create and assign html to widget
>         html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
>         #     html = '<button type="button">Click Me!</button><download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
>         htmlWidget.value = html.format(payload=payload, title= filename, filename=filename)
>     else:
>         htmlWidget.value = ''
> 
> 
> class VuetifyTable_pandas_df(v.VuetifyTemplate):
>     """
>     Vuetify DataTable rendering of a pandas DataFrame with similar methods to QGrid
>     
>     Args:
>         data (DataFrame) - the data to render
>         title (str) - optional title
>         multiple (Bool) - True (default) enables multiple line selection
>         dense (Bool) - True (default) enables dense rendering of table
> 
> 
> 
>     Example:
> 
>         import pandas as pd
> 
>         iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
>         test = VuetifyTable_pandas_df(df = iris)
> 
>         test.title = 'sdvsd'
>         test.multiple = True
>         test.dense = True
> 
>         def onChange_table(change,widget):
>         #     print(change['new'])
>             print(widget.value)
> 
>         test.observe(onChange_table,'value',test)
> 
>         test.get_selected_df()
> 
>         test.get_selected_rows()
> 
>     """
>     
>     headers = traitlets.List([]).tag(sync=True, allow_null=True)
>     items = traitlets.List([]).tag(sync=True, allow_null=True)
>     value = traitlets.List([]).tag(sync=True, allow_null=True)
>     search = traitlets.Unicode('').tag(sync=True)
>     title = traitlets.Unicode('').tag(sync=True)
>     index_col = traitlets.Unicode('').tag(sync=True)
>     multiple =  traitlets.Bool(False).tag(sync=True)
>     dense =  traitlets.Bool(False).tag(sync=True)
>     template = traitlets.Unicode('''
>         <template>
>           <v-card>
>             <v-card-title>
>               <span class="title font-weight-bold">{{ title }}</span>
>               <v-spacer></v-spacer>
>                 <v-text-field
>                     v-model="search"
>                     append-icon="mdi-magnify"
>                     label="Search ..."
>                     single-line
>                     hide-details
>                 ></v-text-field>
>             </v-card-title>
>             <v-data-table
>                 :headers="headers"
>                 :items="items"
>                 :search="search"
>                 :item-key="index_col"
>                 :show-select="multiple"
>                 :dense ="dense"
>                 v-model="value"
>                 
>                 
>                 :footer-props="{'items-per-page-options': [10, 25, 50, 250, 500, 1000, 10000]}"
>             >
>                 <template v-slot:no-data>
>                   <v-alert :value="true" color="error" icon="mdi-alert">
>                     Sorry, nothing to display here :(
>                   </v-alert>
>                 </template>
>                 <template v-slot:no-results>
>                     <v-alert :value="true" color="error" icon="mdi-alert">
>                       Your search for "{{ search }}" found no results.
>                     </v-alert>
>                 </template>
>                 <template v-slot:items="rows">
>                   <td v-for="(element, label, index) in rows.item"
>                       @click=cell_click(element)
>                       >
>                     {{ element }}
>                   </td>
>                 </template>
>                 
> 
> 
>             </v-data-table>
>           </v-card>
>         </template>
>         ''').tag(sync=True)
>     
>     def __init__(self, *args, df=pd.DataFrame(), title=None, multiple = True, dense = False, **kwargs):
>         super().__init__(*args, **kwargs)
>         df = df.reset_index()
>         self.index_col = df.columns[0]
>         headers = [{
>               "text": col,
>               "value": col
>             } for col in df.columns]
>         headers[0].update({'align': 'left', 'sortable': True})
>         self.headers = headers
>         self.items = json.loads(
>             df.to_json(orient='records'))
>         if title is not None:
>             self.title = title
> 
>         self.dense = dense
>         self.multiple = multiple
> 
>         self.htmlWidget = widgets.HTML(value='')
>         self.observe(self.onChange_table)
> 
>         # Combine table and widgets
>         self.widgets = v.Card(children=[widgets.VBox([self,
>                                        v.Row(children=[v.Tooltip(
>                                            bottom=True,
>                                            v_slots=[{'name': 'activator', 'variable': 'tooltip', 'children':
>                                                v.Btn(v_on='tooltip.on',
>                                                      color='black',
>                                                      class_='ma-3',
>                                                      icon=True,
>                                                      children=[v.Icon(centre=True,
>                                                                       medium=True,
>                                                                       children=['info'])]
>                                                      )}],
>                                            children=['Select rows and click on link to download a CSV file of the selected rows']
>                                        ),
>                                            self.htmlWidget],
>                                            align="center",
>                                            justify="left")
>                                        ])
>                          ])
> 
>     def get_selected_df(self):
>         if len(self.value) > 0:
>             newDict = {}
>             for k in self.value[0].keys():
>                 newDict[k] = [dictionary[k] for dictionary in self.value]
>             df = pd.DataFrame.from_dict(newDict)
>             df = df.set_index('index')
>             return df
>         else:
>             return []
>     
>     def get_selected_rows(self):
>         return [dictionary['index'] for dictionary in self.value]
> 
>     def onChange_table(self, change):
>         df2download(self.htmlWidget, 'selectedRows.csv', self.get_selected_df())
> ```
> 
> ```python
> import pandas as pd
> 
> iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
> test = VuetifyTable_pandas_df(df = iris)
> 
> test.widgets
> ```
> 
> ```python
> test.title = 'sdvsd'
> test.multiple = True
> test.dense = True
> 
> # example function when table changes
> def onChange_table(change,widget):
>     print(widget.value)
> 
> test.observe(onChange_table,'value',test)
> 
> test.get_selected_df()
> 
> test.get_selected_rows()
> ```

What's the license on this code snippet? I'd like to use this qgrid replacement for my own project

**Comment by DougRzz** [comment]
@trbedwards, I adapted some other unknown licensed code to get to what I posted above . So the licensing is probably not open source. But it could 'inspire' similar code snippets. Code that I write, even in my spare time, can be owned by the company I work for. Sorry, its dodgy ground. Maybe someone else who is more knowledgable about licensing can give you a better answer.

**Comment by tedwards-flf** [comment]
> @trbedwards, I adapted some other unknown licensed code to get to what I posted above . So the licensing is probably not open source. But it could 'inspire' similar code snippets. Code that I write, even in my spare time, can be owned by the company I work for. Sorry, its dodgy ground. Maybe someone else who is more knowledgable about licensing can give you a better answer.

It turns out there's a [vue datatable example](https://github.com/mariobuikhuizen/ipyvuetify/blob/master/examples/Examples%20template.ipynb) in the ipvuetify repository, so I'll start with that instead. Thanks anyway
