### ISSUE TITLE
Is it possible to import other vue related libraries

### ISSUE THREAD

**Issue by beader** [mariobuikhuizen/ipyvuetify#77]
Hi, thank you for this amazing package.

Is it possible to import some other 3rd-party vue related library like [v-charts](https://github.com/ElemeFE/v-charts) and [vue-echarts](https://github.com/ecomfe/vue-echarts) in `VuetifyTemplate` ? 

Thank you very much.

**Comment by mariobuikhuizen** [comment]
It's great to hear you like it!

No, this is not possible.

You can create a jupyter extension like is done in https://github.com/nmearl/ipygoldenlayout, then you can use the components from that extension in `VuetifyTemplate`
