### ISSUE TITLE
Widget are only displayed in voilà

### ISSUE THREAD

**Issue by 12rambau** [mariobuikhuizen/ipyvuetify#78]
Following the instructions find in the [Doc](https://ipyvuetify.readthedocs.io/en/latest/usage.html#create-an-ipyvuetify-widget) I wanted to use `ipyvuetify` to create an autonomous dashboard. 
I want to do some experiments without launching the `voila` dashboard as shown in this [video](https://youtu.be/VtchVpoSdoQ?t=852).   
Unfortunately when I launch my cells in my jupyter notebook nothing is displayed.

voilà 
![Capture d’écran 2020-07-03 à 10 50 59](https://user-images.githubusercontent.com/12596392/86451441-38077180-bd1b-11ea-8fec-f38702c08fce.png)
notebook
![Capture d’écran 2020-07-03 à 10 51 06](https://user-images.githubusercontent.com/12596392/86451444-38a00800-bd1b-11ea-8c20-c16f001a2e42.png)

Do you have any Idea what i could do wrong ?

**Comment by DougRzz** [comment]
@12rambau You probably just need to restart Jupyter and make sure the ipyvuetify is enabled as an nb extension.

**Comment by 12rambau** [comment]
So I restarted my Jupyter notebook and effectively `ipyvuetify` is not enable as an nb extention. 
I tried to run the command  
```bash 
$ jupyter nbextension enable ipyvuetify
```
but I get the following error : 
>Enabling notebook extension ipyvuetify...
>  - Validating: problems found:
>    - require?  X ipyvuetify

I must confess that I don't event know what is an  `nb extention`. To install the module, I just used your [doc](https://ipyvuetify.readthedocs.io/en/latest/installation.html#jupyter-lab) that don't mention it...

**Comment by maartenbreddels** [comment]
it should not be needed, only for really old notebook versions or dev install (`pip install -e .`)

**Comment by 12rambau** [comment]
I restated the notebook again and checked the nb extentions : 
`ipyvuetify` is now configured and enabled. I doesn't change the output though, I still manage to display the widget in voilà but not in the notebook

**Comment by maartenbreddels** [comment]
did you refresh the page?

**Comment by 12rambau** [comment]
yes, out of curiosity I ran: 
```
$ jupyter nbextension list
```

and get 
```
Known nbextensions:
  config dir: /home/prambaud/.jupyter/nbconfig
    notebook section
      bqplot/extension disabled
      latex_envs/latex_envs disabled
      ipyvuetify  enabled 
      - Validating: problems found:
        - require?  X ipyvuetify
  config dir: /usr/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      voila/extension  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      bqplot/extension  enabled 
      - Validating: OK
      ipytree/extension  enabled 
      - Validating: OK
      jupyter-leaflet/extension  enabled 
      - Validating: OK
      voila/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled 
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```

I see that there is still a problem but I don't know what to think of it

**Comment by maartenbreddels** [comment]
I see you installed as a user, then you should be consistent and user `--user` also with the install and enable commands. Btw, I totally discourage `pip install --user`, please consider using virtual envs or conda.

**Comment by 12rambau** [comment]
I'm working on a cloud based Jupyter noteBook so I'm forced to use --user

**Comment by 12rambau** [comment]
So I tried to reinstall everything from scratch : 
```bash
$ pip uninstall ipyvuetify
$ pip intall ipyvuetify
```

But the intall was still done as a user because : 
```bash
Defaulting to user installation because normal site-packages is not writeable
```

I must add that This jupyter notebook is installed through the cloud based application of my company so I can't access everything

but why would the `--user` install prevent my notebook from validating the package ?

**Comment by maartenbreddels** [comment]
Yeah, that's horrible behaviour 😢 
Why don't you try virtualenv? Although I agree, it should work.

**Comment by 12rambau** [comment]
Mainly because I don't know how to use it, currently reading the doc

**Comment by 12rambau** [comment]
I will make no sense as my session is restarted everytime I'm jumping from a AWS computer to another

I tried 
```
$ jupyter nbextension install ipyvuetify --user
```

And I get :
```
Copying: ipyvuetify -> /home/prambaud/.local/share/jupyter/nbextensions/ipyvuetify
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 711, in start
    self.install_extensions()
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 690, in install_extensions
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 194, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 1041, in _maybe_copy
    shutil.copy2(src, dest)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'ipyvuetify'
```

I verified and the folder `/home/prambaud/.local/share/jupyter/nbextensions/ipyvuetify` so maybe the installation is incomplete

**Comment by maartenbreddels** [comment]
could be a pip issue, could you try copying it manually?

**Comment by maartenbreddels** [comment]
or upgrade pip?

**Comment by 12rambau** [comment]
I've done all the installation manually : 
```
$ jupyter nbextension install --user --py --sys-prefix ipyvuetify
$ jupyter nbextension enable --py --sys-prefix ipyvuetify
```

and now it' validated in the list (and enabled)


When I launch the voilà dashboard it's still working flawlessly but in the notebook it never finishes to execute the import cell
```
import ipyvuetify as v
```

**Comment by maartenbreddels** [comment]
Then I think you have an error in the js console, your notebook might be broken. Can you share a screenshot of the error?

**Comment by 12rambau** [comment]
![Capture d’écran 2020-07-03 à 15 41 23](https://user-images.githubusercontent.com/12596392/86474703-aa8c4780-bd43-11ea-801c-cd6c71aac661.png)

**Comment by maartenbreddels** [comment]
I have no idea what is going on, for sure it is not correct, I don't think the extension is enabled. It should try to fetch `nbextensions/ipyvuetify/extension.js` not ipyvuetify.js

**Comment by 12rambau** [comment]
I'll make a proper template to justify the usage of your lib so that I can justify to my boss an complete (and proper) installation

**Comment by mariobuikhuizen** [comment]
I also see ipyvue is not installed/enabled. That should have installed automatically when installing ipyvuetify, but looks like it didn't happen here.

**Comment by maartenbreddels** [comment]
good catch



Op vr 3 jul. 2020 om 20:49 schreef Mario Buikhuizen <
notifications@github.com>:

**Comment by mariobuikhuizen** [comment]
In case the jupyter-server is on another machine than the kernels, ipyvuetify and ipyvue should be installed on both machines.

**Comment by maartenbreddels** [comment]
or in different environments (more common)




Op za 4 jul. 2020 om 19:27 schreef Mario Buikhuizen <
notifications@github.com>:

**Comment by 12rambau** [comment]
Finally had the authorization for an  installation without defaulting to `--user` it work well and I can finally see my widgets.   
Thx for your help

**Comment by maartenbreddels** [comment]
Thanks for the update!
