### ISSUE TITLE
Is it possible to bind the widget's v-model to a single variable ?

### ISSUE THREAD

**Issue by 12rambau** [mariobuikhuizen/ipyvuetify#81]
Is possible to bind the widget's `v-model` to a single variable using `v.jslink` ? 
like : 
```py

color_select = v.Select(
    v_model='green',
    label='Colors',
    items=['red', 'green', 'blue'])

toto = None
v.jslink((color_select, 'v_model'), toto)
```
Sorry but I cannot test it because of #78 ....

Then These question are more usage related do I need to put them on StackOverflow ? (didn't find the `ipyvuetify` tag so I ended up here)

**Comment by mariobuikhuizen** [comment]
It's fine to ask questions here for now, thanks for asking.

No, `ipywidgets.jslink` (not `v.jslink`) can only link two traitlets.

It is possible to set the variable by observing v_model with (only sync in one direction):
```python
color_select = v.Select(
    v_model='green',
    label='Colors',
    items=['red', 'green', 'blue'])

toto = None

def _color_changed(change):
    global toto
    toto = change['new']

color_select.observe(_color_changed, 'v_model')

color_select
``` 

Or make a class with a traitlet and link to that:
```
import traitlets
import ipywidgets as widgets

class TotoContainer(traitlets.HasTraits):
    toto = traitlets.Unicode(None, allow_none=True).tag(sync=True)

my_toto = TotoContainer() 

widgets.link((color_select, 'v_model'), (my_toto, 'toto'))
```

You can try this on binder until ipyvuetify works on your company's setup: https://mybinder.org/v2/gh/mariobuikhuizen/ipyvuetify/master?filepath=examples%2FExamples.ipynb

**Comment by 12rambau** [comment]
I will stay with the first one, I don't really need it to be bidirectional in fact. 

thank you for the binder, it actually very useful !
