### ISSUE TITLE
Is it possible to parse pure Html or Markdown ?

### ISSUE THREAD

**Issue by 12rambau** [mariobuikhuizen/ipyvuetify#84]
I'd like to create a tile in my voilà notebook that display lots of information to the user. It's a long text with titles, links, bullet points and everything.

It's super easy to write down in pure html or markdown but become super messy when I move to Ipyvuetify as I need to use a `v.Html(tag="xx")` every time I'm changing element. 

Is there a way to simply insert a pure html static text in an element to be display?

**Comment by mariobuikhuizen** [comment]
You can use ipywigets HTML widget https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#HTML for static HTML.

Or you can use the template version of ipyvuetify if parts of the HTML change, see https://github.com/mariobuikhuizen/ipyvuetify#alternate-usage and https://github.com/mariobuikhuizen/ipyvuetify/blob/master/examples/Examples%20template.ipynb.

```python
import traitlets
import ipyvuetify as v

class MyHTML(v.VuetifyTemplate):
    template = traitlets.Unicode('''
        <template>
            <div>
                <h2>{{ title }}</h2>
                <ul>
                    <li v-for="item in items" :key="item">
                        {{ item }}
                    </li>
                </ul>
            <div>    
        </template>
    ''').tag(sync=True)
    
    title = traitlets.Unicode().tag(sync=True)
    items = traitlets.List().tag(sync=True)
    
myhtml = MyHTML(title='My list', items=['item a', 'item b', 'item c'])
myhtml
```
And then you can change parts:
```python
myhtml.title = "Something else"
```

**Comment by 12rambau** [comment]
As it was static html the ipywigets HTML widget was exactly what I needed. Combined with the [markdown python library](https://github.com/Python-Markdown/markdown), I can parse .md file into html element and display them in my notebook.  

Thanks 

```
#read the content and transform it into a html
    f = open(pathname, 'r')
    if f.mode == 'r':
        about = f.read()
    else :
        about = '**No About File**'
        
    about = markdown(about, extensions=['fenced_code', 'sane_lists'])
    
    #create a Html widget
    content = w.HTML(value=about)
```
