### ISSUE TITLE
DataTable with ipywidget items

### ISSUE THREAD

**Issue by bdch1234** [mariobuikhuizen/ipyvuetify#86]
Hi,

I would like to create a DataTable but where instead of passing items as a json string, I would pass a list of jupyter-widgets (where each field is synced and corresponds to a name in the headers). The reasoning would be that I want to use the jsdlink functionality in widgets to auto-update the tables values, and also possibly have child-widgets to the item-widgets rendering. Could you point me in the right direction?

Thanks

**Comment by mariobuikhuizen** [comment]
Sadly this is not possible. The items attribute can't handle widgets.

**Comment by maartenbreddels** [comment]
I guess.you could do sth.like this with a template right?

(from mobile phone)

**Comment by bdch1234** [comment]
Yes, it is definitely possible to render standard widgets in the data-cells. Doing this renders HTML-widgets in each cell:
```python
class MyTable(v.VuetifyTemplate):
    headers = traitlets.List([{'text': 'MyData', 'value': 'mydata'},{'text': 'MyField', 'value': 'myfield'}]).tag(sync=True, allow_null=True)
    items = traitlets.List([{'mydata': 'Item1'}]).tag(sync=True, allow_null=True)
    template = traitlets.Unicode('''
        <template>
            <v-data-table
                :headers="headers"
                :items="items"
            >
                <template #item.myfield="{item}">
                    <mywidget />
                </template>
            </v-data-table>
        </template>
        ''').tag(sync=True)

MyTable(components={'mywidget': widgets.HTML('TestString')})
```
But I haven't figured out a way to make each instance of mywidget unique to each item.

**Comment by bdch1234** [comment]
I ended up using below, if you think of a better solution then please let me know.
```python
class MyTable(v.VuetifyTemplate):
    headers = traitlets.List([{'text': 'MyData', 'value': 'mydata'},{'text': 'MyField', 'value': 'myfield'}]).tag(sync=True, allow_null=True)
    items = traitlets.List([{'mydata': 'Item1'}, {'mydata': 'Item2'}]).tag(sync=True, allow_null=True)
    template = traitlets.Unicode('''
        <template>
            <v-data-table
                :headers="headers"
                :items="items"
            >
                <template #item.myfield="{item}">
                    <mywidget v-if="item.mydata=='Item1'"/>
                    <mywidget2 v-else-if="item.mydata=='Item2'"/>
                </template>
            </v-data-table>
        </template>
        ''').tag(sync=True)

MyTable(components={'mywidget': widgets.HTML('TestString'), 'mywidget2': widgets.HTML('TestString2')})
```

**Comment by bdch1234** [comment]
Hi guys, I think I need some help here. The solution I had above didn't scale very well with the number of items in the table, so I started doing something like below instead. Starting with just a vuetify-slider instead of ipywidget to see if I could solve the issue of getting each item stateful, but I couldn't get it to work (sliders are linked, where I was hoping to get them set to the index of the item below). Do you have any input on how I can take this further?

```python
class MyDataTable(v.VuetifyTemplate):
    headers = List([{'text': 'Col1', 'value':'c1'}, {'text': 'Col2', 'value':'c2'}]).tag(sync=True)
    items = List([{'id': 0, 'c1': 'x1'}, {'id': 1, 'c1': 'x2'}]).tag(sync=True)
    template = Unicode('''
    <template>
        <v-data-table
            :headers="headers"
            :items="items">
            <template #item.c2="{item}">
                <myslider v-model="item.id" />
            </template>
        </v-data-table>
    </template>
    ''').tag(sync=True)
    
MyDataTable(components={'myslider': v.Slider(v_model=25)})
```

**Comment by martin-loland-4ss** [comment]
>  to see if I could solve the issue of getting each item stateful

Have you found a way to accomplish this? In Vue native language it's possible to pass properties to custom components. Is this not possible in ipyvuetify?

**Comment by bdch1234** [comment]
@martin-loland-4ss, I haven't found a solution for this. Haven't been looking much more into it either, since I decided to use something else instead.

**Comment by samiit** [comment]
Hi @bdch1234 

Would you mind sharing what solution you found? What else did you decide to use?

Thanks,
Sam

**Comment by bdch1234** [comment]
Hi @samiit, I switched to using [ipysheet](https://github.com/QuantStack/ipysheet) instead.

**Comment by samiit** [comment]
Thanks @bdch1234 .
Unfortunately, I've not had very good experience with ipysheet, mainly while using it within ipyvuetify, especially while using categorical entries, for which a cell might have different options to choose from, e.g., the arrow does not work.
Additionally, the entries in the sheet get deleted, the moment I choose another item in the categorical cell. How has been your experience with categorical entries in a cell?

Thanks,
Sam

**Comment by bdch1234** [comment]
@samiit another package which I think looks very promising is [ipydatagrid](https://github.com/bloomberg/ipydatagrid), you might want to check that out.
