### ISSUE TITLE
Is it possible to trigger the resize event ?

### ISSUE THREAD

**Issue by 12rambau** [mariobuikhuizen/ipyvuetify#90]
I'm using the ipyvuetify widgets as a templates to create tiles. 
I change the visibility of these tiles by adding/removing the 'd-none' property to their `class_`.

Unfortunately if a tile contains a bqplot or a ipyleaflet map, I get a badly tiled map or a blank plot. 

I think these elements are waiting for the "resize" js event to actually recompute the display. For example I also have a drawer menu and when I open it the maps are recomputing their display.

Is there a way to manually trigger this event within a notebook ?

**Comment by mariobuikhuizen** [comment]
You could try to trigger a browser resize event:
```python
class ResizeTrigger(v.VuetifyTemplate):
    template = traitlets.Unicode('''
    <template>
    </template>
    <script>
        modules.export = {
            watch: {
                resize() {
                    window.dispatchEvent(new Event('resize'));
                }
            }
        }
    </script>
    ''').tag(sync=True)
    
    
    resize = traitlets.Int(0).tag(sync=True)

    
rt = ResizeTrigger()
rt

```

```python
rt.resize += 1
```

**Comment by guimillet** [comment]
Is adding 'd-none' in the `class_ ` attribute of an ipyvuetify widget the only way to hide it?

Once a widget is in an ipyvuetify container (for example, Container, Row, App), the methods [known for ipywidgets](https://stackoverflow.com/q/38964323) stop working. Is it normal?

```python
import ipywidgets as w
import ipyvuetify as v

#ipyvuetify
def ipyvue_visi(widget, event, dat):
    widget.layout.visibility = 'hidden'
def ipyvue_disp(widget, event, dat):
    widget.layout.display = 'none'
def ipyvue_close(widget, event, dat):
    widget.close()
def ipyvue_class(widget, event, dat):
    widget.class_ = str(widget.class_).strip() + ' d-none'

visi_btn = v.Btn(children=["visibility='hidden'"])
visi_btn.on_event('click',ipyvue_visi)

disp_btn = v.Btn(children=["display='none'"])
disp_btn.on_event('click',ipyvue_disp)

close_btn = v.Btn(children=["close()"])
close_btn.on_event('click',ipyvue_close)

class_btn = v.Btn(children=["add d-none to class_"])
class_btn.on_event('click',ipyvue_class)

cont = v.Row(children=[visi_btn, disp_btn, close_btn, class_btn])

#ipywidget
def ipywid_visi(b):
    w_visi_btn.layout.visibility = 'hidden'
def ipywid_disp(b):
    w_disp_btn.layout.display = 'none'
def ipywid_close(b):
    w_close_btn.close()

w_visi_btn = w.Button(description="visibility='hidden'")
w_visi_btn.on_click(ipywid_visi)

w_disp_btn = w.Button(description="display='none'")
w_disp_btn.on_click(ipywid_disp)

w_close_btn = w.Button(description="close()")
w_close_btn.on_click(ipywid_close)

w_cont = w.HBox([w_visi_btn, w_disp_btn, w_close_btn])

display(
    w.Label('ipyvuetify components'),visi_btn, disp_btn, close_btn, class_btn, cont,
    w.Label('ipywidget components'), w_visi_btn, w_disp_btn, w_close_btn, w_cont,
)
```
In the above example, the first three buttons in the ipyvuetify Row stay visible after clicking on them, whereas the buttons in the HBox ipywidget are hidden after clicking on them.

**Comment by 12rambau** [comment]
This question is absolutely unrelated to mine. It clearly deserve its own. 
I suggest you post it in a new issue or ask it on Stackoverflow using `vuetify.js`, `python`and `ipywidget` tags

**Comment by guimillet** [comment]
Sorry, I will create a new post and delete my comments here.
