### ISSUE TITLE
The max_height parameter of a v.List is not respected

### ISSUE THREAD

**Issue by 12rambau** [mariobuikhuizen/ipyvuetify#94]
I try to create a file selector inspired by [crahan/ipyfilechooser](https://github.com/crahan/ipyfilechooser). 

so when the folder content is too big I want to create a scrollable list : 
```
folder_select = v.Select(items=get_parent_path('/home/prambaud'), label='folder', v_model='/home/prambaud')
file_list = v.List(
    dense=True, 
    color='grey lighten-4', 
    max_height='300px',
    flat=True,
    children=[
        v.ListItemGroup(
            active_class="border",
            children=get_items('/home/prambaud/'),
            v_model=None
        )
    ]
)
```

displaying the separately give me the exact behaviour I need : the folder selector stays on top and I can scroll in the items
```
display(folder_select)
display(file_list)
```

<img width="1000" alt="Capture d’écran 2020-10-07 à 10 59 28" src="https://user-images.githubusercontent.com/12596392/95310077-40c49200-088c-11eb-8c7f-1e780fc4d2c7.png">

But I need to add them in a single widget to use them as a standalone input component so I created a layout :
```
file_input = v.Layout(
    v_model=None,
    row=True,
    class_='pa-5',
    align_center=True,
    style_='300px',
    children=[
        v.Flex(xs12=True, children=[folder_select]),
        v.Flex(xs12=True, children=[file_list])
    ]
)
```
and max_heigth parameter is not respected any more and all the layout become scrollable instead of just the file list : 

<img width="997" alt="Capture d’écran 2020-10-07 à 11 02 25" src="https://user-images.githubusercontent.com/12596392/95310401-a6188300-088c-11eb-843a-4b9496c32475.png">

it's even worse if i try to include it in a more complex layout : 
<img width="977" alt="Capture d’écran 2020-10-07 à 11 03 38" src="https://user-images.githubusercontent.com/12596392/95310513-c7796f00-088c-11eb-8678-40677ec18e08.png">

Is it a known bug ? Is there a way to create a scrollable Layout inside another Layout ?

**Comment by mariobuikhuizen** [comment]
You will need to set the style `overflow: auto` to hide the overflowing content and show a scrollbar.

```python
...
   max_height='300px',
   style_='overflow: auto',
...   
````
