### ISSUE TITLE
Drop-in replacement for ipywidgets.HTML?

### ISSUE THREAD

**Issue by sradomski** [mariobuikhuizen/ipyvuetify#99]
Hey there,

I was trying to take advantage of the [general typography](https://vuetifyjs.com/en/styles/text-and-typography/#typography) features of vuetify to have more pleasing blocks of text. At the moment, I am using `ipywidgets.HTML` to render my text:

```
import ipywidgets as widgets
widgets.HTML("""
<h1>Foo</h1>
<p>
    See some link <a>here</a>.
</p>
""")
```

but it looks .. unspectacular. How would I use the typography styles of vuetify via ipyvuetify? I have seen [one approach](https://github.com/mariobuikhuizen/ipyvuetify/issues/84) using a `VuetifyTemplate`, but that seems a tad too complicated for simple styled HTML.

Regards
Stefan

**Comment by DohunLee** [comment]
Hi @sradomski ,

you can use the `v.Html()`  option as explained here https://ipyvuetify.readthedocs.io/en/latest/usage.html#regular-html-tags.
There you can use all the HTML tags and for text formatting all the css tags.

**Comment by sradomski** [comment]
Thank you!

It may be worth mentioning in the docs that you can also pass attributes:

```
v.Container(children=[
    v.Html(tag='h1', children=['Foo']),
    v.Html(tag='a', children=['link'], attributes={'href':"https://www.github.com"}),
])

```
